#!/usr/bin/env python3
"""Protobuf Python benchmark target.

Encodes + decodes the canonical FullScaleExample message (schema/state.json)
through protobuf's generated `message_pb2`. Same message, same state, same
timed region as the SofaBuffers target. Prints one uniform BENCH line.
"""
import hashlib
import json
import os
import sys
import time

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "gen"))
import message_pb2 as pb  # generated by protoc  # noqa: E402


def build(state) -> "pb.FullScaleExample":
    m = pb.FullScaleExample()
    for k in ("u8", "i8", "u16", "i16", "u32", "i32", "u64", "i64"):
        setattr(m, k, state[k])
    n = state["nested"]
    m.nested.f32 = n["f32"]
    m.nested.f64 = n["f64"]
    setattr(m.nested, "str", n["str"])
    m.nested.bytes_field = bytes(n["bytes_field"])
    a = state["arrays"]
    for k in ("u8", "i8", "u16", "i16", "u32", "i32", "u64", "i64"):
        getattr(m.arrays, k).extend(a[k])
    m.arrays.nested.fp32.extend(a["nested"]["fp32"])
    m.arrays.nested.fp64.extend(a["nested"]["fp64"])
    m.string_array.strings.extend(state["string_array"])
    return m


def main() -> int:
    state = json.load(open(os.environ["STATE_JSON"]))
    src = build(state)

    blob = src.SerializeToString()
    serialized = len(blob)
    sha = hashlib.sha256(blob).hexdigest()
    chk = pb.FullScaleExample()
    chk.ParseFromString(blob)
    if chk.SerializeToString() != blob:
        sys.stderr.write("FAIL: protobuf round-trip self-check\n")
        return 1

    iters = int(os.environ.get("BENCH_ITERS", "200000"))
    dec = pb.FullScaleExample()
    t0 = time.process_time()
    for _ in range(iters):
        b = src.SerializeToString()
        dec.ParseFromString(b)
    t1 = time.process_time()

    cpu = t1 - t0
    mbs = (serialized * iters / cpu / 1e6) if cpu > 0 else 0.0
    print(f"BENCH lang=python impl=protobuf serialized_bytes={serialized} "
          f"iters={iters} cpu_time_s={cpu:.6f} throughput_mbs={mbs:.2f} sha256={sha}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
