// EmbeddedProto benchmark target (cpp-embedded arena).
//
// Encodes + decodes the canonical FullScaleExample message through the
// EmbeddedProto generated C++ types (no dynamic allocation, fixed-size
// buffers). Values are identical to every other target in the arena. Prints
// one uniform BENCH line (docs/BENCH.md).
//
// EmbeddedProto is GPLv3 and is used at BUILD TIME ONLY (generated headers +
// header/source runtime compiled into this bench); it is never redistributed.
#ifndef _POSIX_C_SOURCE
#  define _POSIX_C_SOURCE 199309L
#endif

#include <cfloat>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>

#include "message.h"                 // generated by protoc-gen-eams
#include "WriteBufferFixedSize.h"
#include "ReadBufferFixedSize.h"
#include "sha256.h"

using fullscale::FullScaleExample;

namespace {

// Generous fixed buffer: the canonical message encodes to 494 bytes.
constexpr std::uint32_t BUFSZ = 1024;

double now_seconds()
{
    struct timespec ts;
    clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &ts);
    return static_cast<double>(ts.tv_sec) + static_cast<double>(ts.tv_nsec) / 1.0e9;
}

long bench_iters(long fallback)
{
    const char *s = getenv("BENCH_ITERS");
    if (s != nullptr && s[0] != '\0') {
        long v = atol(s);
        if (v > 0) {
            return v;
        }
    }
    return fallback;
}

void fill(FullScaleExample &m)
{
    m.set_u8(200);
    m.set_i8(-100);
    m.set_u16(50000);
    m.set_i16(-20000);
    m.set_u32(3000000000U);
    m.set_i32(-1000000000);
    m.set_u64(10000000000000ULL);
    m.set_i64(-5000000000000LL);

    auto &nested = m.mutable_nested();
    nested.set_f32(3.14f);
    nested.set_f64(3.14159265);
    nested.mutable_str() = "Hello, World!";
    const std::uint8_t blob[4] = {0xDE, 0xAD, 0xBE, 0xEF};
    nested.mutable_bytes_field().set(blob, 4);

    const uint8_t  u8v[5]  = {0, 64, 128, 191, 255};
    const int8_t   i8v[5]  = {-128, -64, 0, 63, 127};
    const uint16_t u16v[5] = {0, 16384, 32768, 49151, 65535};
    const int16_t  i16v[5] = {-32768, -16384, 0, 16383, 32767};
    const uint32_t u32v[5] = {0, 1073741824U, 2147483648U, 3221225471U, 4294967295U};
    const int32_t  i32v[5] = {INT32_MIN, -1073741824, 0, 1073741823, INT32_MAX};
    const uint64_t u64v[5] = {0ULL, 4611686018427387904ULL, 9223372036854775808ULL,
                              13835058055282163711ULL, 18446744073709551615ULL};
    const int64_t  i64v[5] = {-9223372036854775807LL, -4611686018427387904LL, 0LL,
                              4611686018427387903LL, 9223372036854775807LL};
    const float    fp32v[5] = {1.0f, 2.0f, 3.0f, -FLT_MAX, FLT_MAX};
    const double   fp64v[5] = {1.0, 2.0, 3.0, -DBL_MAX, DBL_MAX};

    auto &arr = m.mutable_arrays();
    for (std::uint32_t i = 0; i < 5; ++i) {
        arr.add_u8(static_cast<uint32_t>(u8v[i]));
        arr.add_i8(static_cast<int32_t>(i8v[i]));
        arr.add_u16(static_cast<uint32_t>(u16v[i]));
        arr.add_i16(static_cast<int32_t>(i16v[i]));
        arr.add_u32(u32v[i]);
        arr.add_i32(i32v[i]);
        arr.add_u64(u64v[i]);
        arr.add_i64(i64v[i]);
        arr.mutable_nested().add_fp32(fp32v[i]);
        arr.mutable_nested().add_fp64(fp64v[i]);
    }

    const char *strs[5] = {
        "Hello, Sofab!",
        "",
        "1234567890",
        "\xC3\xA4\xC3\xB6\xC3\xBC\xC3\x84\xC3\x96\xC3\x9C\xC3\x9F", // "äöüÄÖÜß"
        "This_is_a_very_long_test_string_with_!@#$%^&*()_+-=[]{}",
    };
    auto &sa = m.mutable_string_array();
    for (std::uint32_t i = 0; i < 5; ++i) {
        ::EmbeddedProto::FieldString<64> f;
        f = strs[i];
        sa.add_strings(f);
    }
}

// Encode m into out (BUFSZ bytes). Returns serialized length, or 0 on error.
std::uint32_t encode(const FullScaleExample &m, std::uint8_t *out)
{
    ::EmbeddedProto::WriteBufferFixedSize<BUFSZ> wbuf;
    wbuf.clear();
    if (m.serialize(wbuf) != ::EmbeddedProto::Error::NO_ERRORS) {
        return 0;
    }
    const std::uint32_t n = wbuf.get_size();
    memcpy(out, wbuf.get_data(), n);
    return n;
}

// Decode len bytes at data into m. Returns true on success.
bool decode(FullScaleExample &m, const std::uint8_t *data, std::uint32_t len)
{
    ::EmbeddedProto::ReadBufferFixedSize<BUFSZ> rbuf;
    memcpy(rbuf.get_data(), data, len);
    rbuf.set_bytes_written(len);
    m.clear();
    return m.deserialize(rbuf) == ::EmbeddedProto::Error::NO_ERRORS;
}

} // namespace

int main()
{
    FullScaleExample src;
    fill(src);

    // Warm-up encode + self-check (outside the timed region).
    std::uint8_t bytes[BUFSZ];
    const std::uint32_t serialized = encode(src, bytes);
    if (serialized == 0) {
        fprintf(stderr, "FAIL: embeddedproto encode\n");
        return 1;
    }
    char sha[65];
    sha256_hex(bytes, serialized, sha);

    // Round-trip is correct iff the decoded message re-encodes to the same bytes.
    FullScaleExample check;
    if (!decode(check, bytes, serialized)) {
        fprintf(stderr, "FAIL: embeddedproto decode\n");
        return 1;
    }
    std::uint8_t rebytes[BUFSZ];
    const std::uint32_t reserialized = encode(check, rebytes);
    if (reserialized != serialized || memcmp(bytes, rebytes, serialized) != 0) {
        fprintf(stderr, "FAIL: embeddedproto round-trip self-check\n");
        return 1;
    }

    // Timed loop: ONLY encode + decode.
    FullScaleExample dec;
    std::uint8_t buf[BUFSZ];
    const long iters = bench_iters(500000);
    const double t0 = now_seconds();
    for (long i = 0; i < iters; ++i) {
        const std::uint32_t n = encode(src, buf);
        decode(dec, buf, n);
    }
    const double t1 = now_seconds();

    std::uint8_t last[BUFSZ];
    const std::uint32_t lastn = encode(dec, last);
    if (lastn != serialized || memcmp(bytes, last, serialized) != 0) {
        fprintf(stderr, "FAIL: embeddedproto loop-path self-check\n");
        return 1;
    }

    const double cpu = t1 - t0;
    const double mbs = (cpu > 0.0)
        ? static_cast<double>(serialized) * static_cast<double>(iters) / cpu / 1.0e6
        : 0.0;
    printf("BENCH lang=cpp-embedded impl=embeddedproto serialized_bytes=%u iters=%ld "
           "cpu_time_s=%.6f throughput_mbs=%.2f sha256=%s\n",
           serialized, iters, cpu, mbs, sha);
    return 0;
}
