#!/usr/bin/env bash
# Zig target setup: generate sofab project + build zig-protobuf baseline. Idempotent.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
SOFABGEN="${SOFABGEN:-$ROOT/tools/sofabgen}"
CORELIB="$ROOT/vendor/corelib-zig"

# --- sofab: generate the typed message project against corelib-zig ---
"$SOFABGEN" --config "$HERE/sofab/cfg.yaml" --lang zig \
    --in "$ROOT/schema/message.sofab.yaml" --out "$HERE/sofab/gen" >/dev/null

# build.zig.zon path dependencies must be relative to the project root
# (see docs/generator/zig.md), so resolve the ${SOFAB_ZIG_CORELIB} placeholder
# with a computed relative path to the vendored corelib clone.
REL="$(python3 -c "import os,sys; print(os.path.relpath(sys.argv[1], sys.argv[2]))" "$CORELIB" "$HERE/sofab/gen")"
sed -i "s#\${SOFAB_ZIG_CORELIB}#$REL#" "$HERE/sofab/gen/build.zig.zon"

# Rewrite build.zig deterministically (the Rust target's Cargo.toml pattern):
# same shape as the generated scaffold, plus our bench binary next to harness.
cat > "$HERE/sofab/gen/build.zig" <<'EOF'
// @generated by sofabgen, patched by languages/zig/setup.sh (adds `bench`)
const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    // corelib-zig is the max-speed port: --release resolves to ReleaseFast,
    // the configuration the corelib is tuned for. Plain zig build = Debug.
    const optimize = b.standardOptimizeOption(.{ .preferred_optimize_mode = .ReleaseFast });

    // The corelib's own build resolves ReleaseFast via --release (it uses
    // standardOptimizeOption with a preferred mode, not -Doptimize), so only
    // the target is forwarded.
    const sofab = b.dependency("sofa_buffers_corelib", .{
        .target = target,
    }).module("sofab");

    inline for (.{ .{ "harness", "src/main.zig" }, .{ "bench", "src/bench.zig" } }) |spec| {
        const mod = b.createModule(.{
            .root_source_file = b.path(spec[1]),
            .target = target,
            .optimize = optimize,
        });
        mod.addImport("sofab", sofab);
        b.installArtifact(b.addExecutable(.{ .name = spec[0], .root_module = mod }));
    }
}
EOF

# Drop our bench binary in beside the generated message module.
cp "$HERE/sofab/bench.zig" "$HERE/sofab/gen/src/bench.zig"

( cd "$HERE/sofab/gen" && zig build --release=fast )

# --- protobuf: zig-protobuf (protoc-gen-zig via `zig build gen-proto`) ---
( cd "$HERE/protobuf" && zig build gen-proto && zig build --release=fast )

echo "zig: setup OK" >&2
