// SofaBuffers C++ benchmark target.
//
// Encodes + decodes the canonical FullScaleExample message (schema/STATE.md)
// through the GENERATED C++ types (fullscale::Example), backed by the pure
// C++20 header-only corelib-cpp. Prints one uniform BENCH line (docs/BENCH.md).
//
// The message fill mirrors every other target in the arena — identical fields,
// ids and values as the .proto / .sofab definitions and the canonical state.
#ifndef _POSIX_C_SOURCE
#  define _POSIX_C_SOURCE 199309L
#endif

#include <cfloat>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <vector>

#include "example.hpp"   // generated by sofabgen (--lang cpp)
#include "sha256.h"

using fullscale::Example;

namespace {

double now_seconds()
{
    struct timespec ts;
    clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &ts);
    return static_cast<double>(ts.tv_sec) + static_cast<double>(ts.tv_nsec) / 1.0e9;
}

long bench_iters(long fallback)
{
    const char *s = getenv("BENCH_ITERS");
    if (s != nullptr && s[0] != '\0') {
        long v = atol(s);
        if (v > 0) {
            return v;
        }
    }
    return fallback;
}

void fill(Example &m)
{
    m.u8  = 200;
    m.i8  = -100;
    m.u16 = 50000;
    m.i16 = -20000;
    m.u32 = 3000000000U;
    m.i32 = -1000000000;
    m.u64 = 10000000000000ULL;
    m.i64 = -5000000000000LL;

    m.nested.f32 = 3.14f;
    m.nested.f64 = 3.14159265;
    m.nested.str = "Hello, World!";
    m.nested.bytes_field = {0xDE, 0xAD, 0xBE, 0xEF};

    const uint8_t  u8v[5]  = {0, 64, 128, 191, 255};
    const int8_t   i8v[5]  = {-128, -64, 0, 63, 127};
    const uint16_t u16v[5] = {0, 16384, 32768, 49151, 65535};
    const int16_t  i16v[5] = {-32768, -16384, 0, 16383, 32767};
    const uint32_t u32v[5] = {0, 1073741824U, 2147483648U, 3221225471U, 4294967295U};
    const int32_t  i32v[5] = {INT32_MIN, -1073741824, 0, 1073741823, INT32_MAX};
    const uint64_t u64v[5] = {0ULL, 4611686018427387904ULL, 9223372036854775808ULL,
                              13835058055282163711ULL, 18446744073709551615ULL};
    const int64_t  i64v[5] = {-9223372036854775807LL, -4611686018427387904LL, 0LL,
                              4611686018427387903LL, 9223372036854775807LL};
    const float    fp32v[5] = {1.0f, 2.0f, 3.0f, -FLT_MAX, FLT_MAX};
    const double   fp64v[5] = {1.0, 2.0, 3.0, -DBL_MAX, DBL_MAX};
    for (size_t i = 0; i < 5; ++i) {
        m.arrays.u8[i]  = u8v[i];   m.arrays.i8[i]  = i8v[i];
        m.arrays.u16[i] = u16v[i];  m.arrays.i16[i] = i16v[i];
        m.arrays.u32[i] = u32v[i];  m.arrays.i32[i] = i32v[i];
        m.arrays.u64[i] = u64v[i];  m.arrays.i64[i] = i64v[i];
        m.arrays.nested.fp32[i] = fp32v[i];
        m.arrays.nested.fp64[i] = fp64v[i];
    }

    m.string_array = {
        "Hello, Sofab!",
        "",
        "1234567890",
        "\xC3\xA4\xC3\xB6\xC3\xBC\xC3\x84\xC3\x96\xC3\x9C\xC3\x9F", // "äöüÄÖÜß"
        "This_is_a_very_long_test_string_with_!@#$%^&*()_+-=[]{}",
    };
}

} // namespace

int main()
{
    Example src;
    fill(src);

    // Warm-up round-trip + self-check (outside the timed region).
    const std::vector<uint8_t> bytes = src.encode();
    const size_t serialized = bytes.size();
    char sha[65];
    sha256_hex(bytes.data(), serialized, sha);

    // Round-trip is correct iff the decoded message re-encodes to the same bytes.
    const Example check = Example::decode(bytes.data(), serialized);
    if (check.encode() != bytes) {
        fprintf(stderr, "FAIL: sofab round-trip self-check\n");
        return 1;
    }

    // Timed loop: chained round trip — decode the reference wire, then re-encode
    // the freshly decoded message (issue #86). Re-encoding a just-decoded message
    // (rather than a pre-built, reused `src`) is what a proxy/transcode does, and
    // it denies protobuf the once-per-instance serialized-size memo, so encode is
    // measured on equal terms across impls.
    Example dec;
    std::vector<uint8_t> b;
    const long iters = bench_iters(500000);
    const double t0 = now_seconds();
    for (long i = 0; i < iters; ++i) {
        dec = Example::decode(bytes.data(), bytes.size());
        b = dec.encode();
    }
    const double t1 = now_seconds();

    if (b != bytes) {
        fprintf(stderr, "FAIL: sofab loop-path self-check\n");
        return 1;
    }

    const double cpu = t1 - t0;
    const double mbs = (cpu > 0.0)
        ? static_cast<double>(serialized) * static_cast<double>(iters) / cpu / 1.0e6
        : 0.0;
    printf("BENCH lang=cpp impl=sofab serialized_bytes=%zu iters=%ld "
           "cpu_time_s=%.6f throughput_mbs=%.2f sha256=%s\n",
           serialized, iters, cpu, mbs, sha);
    return 0;
}
