// SofaBuffers C++ benchmark target.
//
// Encodes + decodes the canonical FullScaleExample message (schema/STATE.md)
// through the GENERATED C++ types (fullscale::Example), backed by the pure
// C++20 header-only corelib-cpp. Prints one uniform BENCH line (docs/BENCH.md).
//
// The message fill mirrors every other target in the arena — identical fields,
// ids and values as the .proto / .sofab definitions and the canonical state.
//
// ONE source, SEVERAL builds: setup.sh compiles this file once per sofab impl of
// the cpp target with identical flags, so the ONLY differences between the runs
// are the macros below and the generated header on the include path. Sharing the
// source — fill, timing, self-checks — is what makes them like-for-like.
//
//   impl=sofab            growable storage (std::string/std::vector), one-shot encode
//   impl=sofab-heapfree   #107: allow_dynamic:false storage (sofab::FixedString/
//                         FixedBytes/InlineVector) — a decode allocates nothing
//   impl=sofab-stream     #108: BENCH_STREAM — the SAME growable storage, but the
//                         encode renders through a bounded buffer drained by a
//                         flush sink instead of one message-sized buffer
#ifndef _POSIX_C_SOURCE
#  define _POSIX_C_SOURCE 199309L
#endif

// Which impl this build measures; set by setup.sh (-DBENCH_IMPL).
#ifndef BENCH_IMPL
#  define BENCH_IMPL "sofab"
#endif

#include <cfloat>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <vector>

#ifdef BENCH_STREAM
#  include <cstring>
#  include <span>
#endif

#include "example.hpp"   // generated by sofabgen (--lang cpp)
#include "sha256.h"

using fullscale::Example;

namespace {

#ifdef BENCH_STREAM
// Streaming encode (#108). encode() above is an OStreamView over a buffer the
// size of the whole message plus serialize(); the streaming path is the SAME
// serialize() over a buffer deliberately SMALLER than the message, handed a flush
// callback that drains it every time it fills. So the encode's memory need is the
// buffer, not the message — the one property that separates this path from the
// one-shot one. STREAM_BUF_BYTES comes from setup.sh so both sides of the row
// (here and protobuf/bench.cpp) drain at the identical granularity.
#  ifndef STREAM_BUF_BYTES
#    define STREAM_BUF_BYTES 64
#  endif

// The drained bytes land here so the loop has a sink that cannot be optimised
// away and the result stays checkable against the reference wire. Sized well
// above the message; the encoder never sees this buffer, only the callback does.
std::uint8_t g_sink[2048];
std::size_t  g_sink_n = 0;

std::size_t stream_encode(const Example &m)
{
    std::uint8_t scratch[STREAM_BUF_BYTES];
    g_sink_n = 0;
    sofab::OStreamView os{
        [](std::span<const std::uint8_t> d) {
            std::memcpy(g_sink + g_sink_n, d.data(), d.size());
            g_sink_n += d.size();
        },
        scratch, sizeof scratch};
    m.serialize(os);
    os.flush();          // hand over the tail still sitting in the buffer
    return g_sink_n;
}
#endif

double now_seconds()
{
    struct timespec ts;
    clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &ts);
    return static_cast<double>(ts.tv_sec) + static_cast<double>(ts.tv_nsec) / 1.0e9;
}

long bench_iters(long fallback)
{
    const char *s = getenv("BENCH_ITERS");
    if (s != nullptr && s[0] != '\0') {
        long v = atol(s);
        if (v > 0) {
            return v;
        }
    }
    return fallback;
}

void fill(Example &m)
{
    m.u8  = 200;
    m.i8  = -100;
    m.u16 = 50000;
    m.i16 = -20000;
    m.u32 = 3000000000U;
    m.i32 = -1000000000;
    m.u64 = 10000000000000ULL;
    m.i64 = -5000000000000LL;

    m.nested.f32 = 3.14f;
    m.nested.f64 = 3.14159265;
    m.nested.str = "Hello, World!";
    m.nested.bytes_field = {0xDE, 0xAD, 0xBE, 0xEF};

    // A fixed `count` array is a length-carrying container (std::vector here,
    // sofab::InlineVector in the fixed-capacity profile), so it starts EMPTY and
    // indexing into it would write out of bounds. Brace assignment sets the
    // elements and the logical length together — same idiom as string_array below.
    m.arrays.u8  = {0, 64, 128, 191, 255};
    m.arrays.i8  = {-128, -64, 0, 63, 127};
    m.arrays.u16 = {0, 16384, 32768, 49151, 65535};
    m.arrays.i16 = {-32768, -16384, 0, 16383, 32767};
    m.arrays.u32 = {0, 1073741824U, 2147483648U, 3221225471U, 4294967295U};
    m.arrays.i32 = {INT32_MIN, -1073741824, 0, 1073741823, INT32_MAX};
    m.arrays.u64 = {0ULL, 4611686018427387904ULL, 9223372036854775808ULL,
                    13835058055282163711ULL, 18446744073709551615ULL};
    m.arrays.i64 = {-9223372036854775807LL, -4611686018427387904LL, 0LL,
                    4611686018427387903LL, 9223372036854775807LL};
    m.arrays.nested.fp32 = {1.0f, 2.0f, 3.0f, -FLT_MAX, FLT_MAX};
    m.arrays.nested.fp64 = {1.0, 2.0, 3.0, -DBL_MAX, DBL_MAX};

    m.string_array = {
        "Hello, Sofab!",
        "",
        "1234567890",
        "\xC3\xA4\xC3\xB6\xC3\xBC\xC3\x84\xC3\x96\xC3\x9C\xC3\x9F", // "äöüÄÖÜß"
        "This_is_a_very_long_test_string_with_!@#$%^&*()_+-=[]{}",
    };
}

} // namespace

int main()
{
    Example src;
    fill(src);

    // Warm-up round-trip + self-check (outside the timed region).
    const std::vector<uint8_t> bytes = src.encode();
    const size_t serialized = bytes.size();
    char sha[65];
    sha256_hex(bytes.data(), serialized, sha);

    // Round-trip is correct iff the decoded message re-encodes to the same bytes —
    // through whichever encode path this build measures, so a streaming encode
    // that drops or duplicates a drained chunk is caught here and not reported.
    const Example check = Example::decode(bytes.data(), serialized);
#ifdef BENCH_STREAM
    if (stream_encode(check) != serialized ||
        std::memcmp(g_sink, bytes.data(), serialized) != 0) {
#else
    if (check.encode() != bytes) {
#endif
        fprintf(stderr, "FAIL: sofab round-trip self-check\n");
        return 1;
    }

    // Timed loop: chained round trip — decode the reference wire, then re-encode
    // the freshly decoded message (issue #86). Re-encoding a just-decoded message
    // (rather than a pre-built, reused `src`) is what a proxy/transcode does, and
    // it denies protobuf the once-per-instance serialized-size memo, so encode is
    // measured on equal terms across impls.
    //
    // The DECODE half is the plain one-shot decode in every build, including the
    // streaming one: this row varies the encode path only, so that is the only
    // thing its number may reflect (#108).
    Example dec;
#ifndef BENCH_STREAM
    std::vector<uint8_t> b;
#endif
    const long iters = bench_iters(500000);
    const double t0 = now_seconds();
    for (long i = 0; i < iters; ++i) {
        dec = Example::decode(bytes.data(), bytes.size());
#ifdef BENCH_STREAM
        stream_encode(dec);
#else
        b = dec.encode();
#endif
    }
    const double t1 = now_seconds();

#ifdef BENCH_STREAM
    if (g_sink_n != serialized || std::memcmp(g_sink, bytes.data(), serialized) != 0) {
#else
    if (b != bytes) {
#endif
        fprintf(stderr, "FAIL: sofab loop-path self-check\n");
        return 1;
    }

    const double cpu = t1 - t0;
    const double mbs = (cpu > 0.0)
        ? static_cast<double>(serialized) * static_cast<double>(iters) / cpu / 1.0e6
        : 0.0;
    // sizeof_bytes is the in-memory size of the message struct — the cost side of
    // the heap-free trade (#107): fixed-capacity storage sizes with the schema's
    // declared count/maxlen instead of with the payload, so it buys the decode
    // speed with RAM. Optional BENCH key; the runner reports it as a footnote.
    printf("BENCH lang=cpp impl=%s serialized_bytes=%zu iters=%ld "
           "cpu_time_s=%.6f throughput_mbs=%.2f sizeof_bytes=%zu sha256=%s\n",
           BENCH_IMPL, serialized, iters, cpu, mbs, sizeof(Example), sha);
    return 0;
}
