// Code generated by sofabgen; DO NOT EDIT.

package message

import (
	"bytes"
	"github.com/sofa-buffers/corelib-go"
	"io"
)

// Example - This example demonstrates the use of SofaBuffers to encode and decode a message.
// Example is a generated SofaBuffers object.
type Example struct {
	U64         uint64        `json:"u64"`
	I64         int64         `json:"i64"`
	Nested      ExampleNested `json:"nested"`
	Arrays      ExampleArrays `json:"arrays"`
	StringArray []string      `json:"string_array"`
	U32         uint32        `json:"u32"`
	I32         int32         `json:"i32"`
	U16         uint16        `json:"u16"`
	I16         int16         `json:"i16"`
	U8          uint8         `json:"u8"`
	I8          int8          `json:"i8"`
}

func (m *Example) marshal(e *sofab.Encoder) {
	if m.U8 != 0 {
		e.WriteUnsigned(0, uint64(m.U8))
	}
	if m.I8 != 0 {
		e.WriteSigned(1, int64(m.I8))
	}
	if m.U16 != 0 {
		e.WriteUnsigned(2, uint64(m.U16))
	}
	if m.I16 != 0 {
		e.WriteSigned(3, int64(m.I16))
	}
	if m.U32 != 0 {
		e.WriteUnsigned(4, uint64(m.U32))
	}
	if m.I32 != 0 {
		e.WriteSigned(5, int64(m.I32))
	}
	if m.U64 != 0 {
		e.WriteUnsigned(6, uint64(m.U64))
	}
	if m.I64 != 0 {
		e.WriteSigned(7, int64(m.I64))
	}
	e.WriteSequenceBegin(10)
	m.Nested.marshal(e)
	e.WriteSequenceEnd()
	e.WriteSequenceBegin(100)
	m.Arrays.marshal(e)
	e.WriteSequenceEnd()
	e.WriteSequenceBegin(200)
	for _i0, _e0 := range m.StringArray {
		e.WriteString(sofab.ID(_i0), _e0)
	}
	e.WriteSequenceEnd()
}

func (m *Example) unmarshal(d *sofab.Decoder) error {
	for {
		fld, err := d.Next()
		if err == io.EOF {
			return nil
		}
		if err != nil {
			return err
		}
		if fld.Type == sofab.TypeSequenceEnd {
			return nil
		}
		switch fld.ID {
		case 0:
			v, _ := d.Unsigned()
			m.U8 = uint8(v)
		case 1:
			v, _ := d.Signed()
			m.I8 = int8(v)
		case 2:
			v, _ := d.Unsigned()
			m.U16 = uint16(v)
		case 3:
			v, _ := d.Signed()
			m.I16 = int16(v)
		case 4:
			v, _ := d.Unsigned()
			m.U32 = uint32(v)
		case 5:
			v, _ := d.Signed()
			m.I32 = int32(v)
		case 6:
			v, _ := d.Unsigned()
			m.U64 = uint64(v)
		case 7:
			v, _ := d.Signed()
			m.I64 = int64(v)
		case 10:
			if err := m.Nested.unmarshal(d); err != nil {
				return err
			}
		case 100:
			if err := m.Arrays.unmarshal(d); err != nil {
				return err
			}
		case 200:
			m.StringArray = m.StringArray[:0]
			for {
				_ef0, _ := d.Next()
				if _ef0.Type == sofab.TypeSequenceEnd {
					break
				}
				_e0, _ := d.String()
				m.StringArray = append(m.StringArray, _e0)
			}
		default:
			if err := d.Skip(); err != nil {
				return err
			}
		}
	}
}

// NewExample returns a Example with schema defaults applied.
func NewExample() *Example {
	m := &Example{}
	return m
}

// Encode serializes the message to bytes.
func (m *Example) Encode() ([]byte, error) {
	var buf bytes.Buffer
	e := sofab.NewEncoder(&buf)
	m.marshal(e)
	if err := e.Flush(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// DecodeExample parses bytes into a new message (with defaults pre-applied).
func DecodeExample(data []byte) (*Example, error) {
	m := NewExample()
	if err := m.unmarshal(sofab.NewDecoder(bytes.NewReader(data))); err != nil {
		return nil, err
	}
	return m, nil
}
