// Code generated by sofabgen; DO NOT EDIT.

package message

import (
	"bytes"
	"github.com/sofa-buffers/corelib-go"
	"io"
)

// Example - This example demonstrates the use of SofaBuffers to encode and decode a message.
// Example is a generated SofaBuffers object.
type Example struct {
	_visitorBase
	U64         uint64        `json:"u64"`
	I64         int64         `json:"i64"`
	Nested      ExampleNested `json:"nested"`
	Arrays      ExampleArrays `json:"arrays"`
	StringArray []string      `json:"string_array"`
	U32         uint32        `json:"u32"`
	I32         int32         `json:"i32"`
	U16         uint16        `json:"u16"`
	I16         int16         `json:"i16"`
	U8          uint8         `json:"u8"`
	I8          int8          `json:"i8"`
}

func (m *Example) Serialize(e *sofab.Encoder) {
	if m.U8 != 0 {
		e.WriteUnsigned(0, uint64(m.U8))
	}
	if m.I8 != 0 {
		e.WriteSigned(1, int64(m.I8))
	}
	if m.U16 != 0 {
		e.WriteUnsigned(2, uint64(m.U16))
	}
	if m.I16 != 0 {
		e.WriteSigned(3, int64(m.I16))
	}
	if m.U32 != 0 {
		e.WriteUnsigned(4, uint64(m.U32))
	}
	if m.I32 != 0 {
		e.WriteSigned(5, int64(m.I32))
	}
	if m.U64 != 0 {
		e.WriteUnsigned(6, uint64(m.U64))
	}
	if m.I64 != 0 {
		e.WriteSigned(7, int64(m.I64))
	}
	e.WriteSequenceBeginLazy(10)
	m.Nested.Serialize(e)
	e.WriteSequenceEnd()
	e.WriteSequenceBeginLazy(100)
	m.Arrays.Serialize(e)
	e.WriteSequenceEnd()
	e.WriteSequenceBeginLazy(200)
	for _i0, _e0 := range m.StringArray {
		if _e0 != "" || _i0 == len(m.StringArray)-1 {
			e.WriteString(sofab.ID(_i0), _e0)
		}
	}
	e.WriteSequenceEnd()
}

func (m *Example) isDefault() bool {
	if !(m.U8 == 0) {
		return false
	}
	if !(m.I8 == 0) {
		return false
	}
	if !(m.U16 == 0) {
		return false
	}
	if !(m.I16 == 0) {
		return false
	}
	if !(m.U32 == 0) {
		return false
	}
	if !(m.I32 == 0) {
		return false
	}
	if !(m.U64 == 0) {
		return false
	}
	if !(m.I64 == 0) {
		return false
	}
	if !(m.Nested.isDefault()) {
		return false
	}
	if !(m.Arrays.isDefault()) {
		return false
	}
	if !(len(m.StringArray) == 0) {
		return false
	}
	return true
}

func (m *Example) Unsigned(id sofab.ID, v uint64) error {
	switch id {
	case 0:
		if v > 255 {
			return sofab.ErrInvalidMsg
		}
		m.U8 = uint8(v)
	case 2:
		if v > 65535 {
			return sofab.ErrInvalidMsg
		}
		m.U16 = uint16(v)
	case 4:
		if v > 4294967295 {
			return sofab.ErrInvalidMsg
		}
		m.U32 = uint32(v)
	case 6:
		m.U64 = uint64(v)
	}
	return nil
}

func (m *Example) Signed(id sofab.ID, v int64) error {
	switch id {
	case 1:
		if v < -128 || v > 127 {
			return sofab.ErrInvalidMsg
		}
		m.I8 = int8(v)
	case 3:
		if v < -32768 || v > 32767 {
			return sofab.ErrInvalidMsg
		}
		m.I16 = int16(v)
	case 5:
		if v < -2147483648 || v > 2147483647 {
			return sofab.ErrInvalidMsg
		}
		m.I32 = int32(v)
	case 7:
		m.I64 = int64(v)
	}
	return nil
}

func (m *Example) BeginSequence(id sofab.ID) (sofab.Visitor, error) {
	switch id {
	case 10:
		return &m.Nested, nil
	case 100:
		return &m.Arrays, nil
	case 200:
		m.StringArray = m.StringArray[:0]
		return &_strSeq{out: &m.StringArray, cap: 5, emax: 64}, nil
	}
	return _visitorBase{}, nil
}

// NewExample returns a Example with schema defaults applied.
func NewExample() *Example {
	m := &Example{}
	return m
}

// Encode serializes the message to bytes.
func (m *Example) Encode() ([]byte, error) {
	var buf bytes.Buffer
	e := sofab.NewEncoder(&buf)
	m.Serialize(e)
	if err := e.Flush(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// EncodeTo serializes the message straight into w.
//
// The encoder drains into w as its internal buffer fills, so the message is
// never held whole in memory: what bounds memory is w, not the message.
// Encode is this with a bytes.Buffer.
func (m *Example) EncodeTo(w io.Writer) error {
	e := sofab.NewEncoder(w)
	m.Serialize(e)
	return e.Flush()
}

// DecodeExample parses bytes into a new message (with defaults pre-applied).
// Decode runs the corelib's zero-copy AcceptBytes cursor over the buffer,
// dispatching each field to the message's sofab.Visitor implementation.
func DecodeExample(data []byte) (*Example, error) {
	m := NewExample()
	if err := sofab.AcceptBytes(data, m); err != nil {
		return nil, err
	}
	return m, nil
}
