// Code generated by sofabgen; DO NOT EDIT.

package message

import (
	"github.com/sofa-buffers/corelib-go"
)

// _isDefaulter is implemented by every generated struct/union type: isDefault
// reports whether the object equals its declared default, compared per child
// field and recursively (S2) -- never as a byte image. It is the explicit form of
// the predicate lazy framing applies implicitly ("not one child was written"),
// generated from the very same per-field expressions the writer uses so the two
// cannot drift apart.
type _isDefaulter interface{ isDefault() bool }

// _caps carries this deployment's receiver-side limits to every corelib
// collector that compares one. A wrapper array's elements never reach the
// callbacks below -- neither their index nor their length word -- so the
// collector gathering them is where those elements are bounded, and these
// are the numbers it bounds them with.
//
// All three entries are filled even where every field of that kind carries a
// schema bound and the entry is never consulted. The library has no fallback
// for a missing one -- it holds no limit of its own and invents none -- so an
// entry left out is a caller mistake (sofab.ErrArgument), not a looser bound.
var _caps = sofab.Caps{ArrayCount: 65536, StringLen: 1048576, BlobLen: 4194304}
