// Code generated by sofabgen; DO NOT EDIT.

package message

import (
	"bytes"
	"github.com/sofa-buffers/corelib-go"
)

// ExampleArrays is a generated SofaBuffers object.
type ExampleArrays struct {
	_visitorBase
	U8     []uint8             `json:"u8"`
	I8     []int8              `json:"i8"`
	U16    []uint16            `json:"u16"`
	I16    []int16             `json:"i16"`
	U32    []uint32            `json:"u32"`
	I32    []int32             `json:"i32"`
	U64    []uint64            `json:"u64"`
	I64    []int64             `json:"i64"`
	Nested ExampleArraysNested `json:"nested"`
}

func (m *ExampleArrays) marshal(e *sofab.Encoder) {
	if len(m.U8) != 0 {
		sofab.WriteUnsignedArray(e, 0, m.U8)
	}
	if len(m.I8) != 0 {
		sofab.WriteSignedArray(e, 1, m.I8)
	}
	if len(m.U16) != 0 {
		sofab.WriteUnsignedArray(e, 2, m.U16)
	}
	if len(m.I16) != 0 {
		sofab.WriteSignedArray(e, 3, m.I16)
	}
	if len(m.U32) != 0 {
		sofab.WriteUnsignedArray(e, 4, m.U32)
	}
	if len(m.I32) != 0 {
		sofab.WriteSignedArray(e, 5, m.I32)
	}
	if len(m.U64) != 0 {
		sofab.WriteUnsignedArray(e, 6, m.U64)
	}
	if len(m.I64) != 0 {
		sofab.WriteSignedArray(e, 7, m.I64)
	}
	e.WriteSequenceBegin(10)
	m.Nested.marshal(e)
	e.WriteSequenceEnd()
}

func (m *ExampleArrays) UnsignedArray(id sofab.ID, v []uint64) error {
	switch id {
	case 0:
		m.U8 = _narrowU[uint8](v)
	case 2:
		m.U16 = _narrowU[uint16](v)
	case 4:
		m.U32 = _narrowU[uint32](v)
	case 6:
		m.U64 = v
	}
	return nil
}

func (m *ExampleArrays) SignedArray(id sofab.ID, v []int64) error {
	switch id {
	case 1:
		m.I8 = _narrowS[int8](v)
	case 3:
		m.I16 = _narrowS[int16](v)
	case 5:
		m.I32 = _narrowS[int32](v)
	case 7:
		m.I64 = v
	}
	return nil
}

func (m *ExampleArrays) BeginSequence(id sofab.ID) (sofab.Visitor, error) {
	switch id {
	case 10:
		return &m.Nested, nil
	}
	return _visitorBase{}, nil
}

// ExampleArraysNested is a generated SofaBuffers object.
type ExampleArraysNested struct {
	_visitorBase
	Fp32 []float32 `json:"fp32"`
	Fp64 []float64 `json:"fp64"`
}

func (m *ExampleArraysNested) marshal(e *sofab.Encoder) {
	if len(m.Fp32) != 0 {
		e.WriteFloat32Array(0, m.Fp32)
	}
	if len(m.Fp64) != 0 {
		e.WriteFloat64Array(1, m.Fp64)
	}
}

func (m *ExampleArraysNested) Float32Array(id sofab.ID, v []float32) error {
	switch id {
	case 0:
		m.Fp32 = v
	}
	return nil
}

func (m *ExampleArraysNested) Float64Array(id sofab.ID, v []float64) error {
	switch id {
	case 1:
		m.Fp64 = v
	}
	return nil
}

// ExampleNested is a generated SofaBuffers object.
type ExampleNested struct {
	_visitorBase
	F64        float64 `json:"f64"`
	Str        string  `json:"str"`
	BytesField []byte  `json:"bytes_field"`
	F32        float32 `json:"f32"`
}

func (m *ExampleNested) marshal(e *sofab.Encoder) {
	if m.F32 != 0 {
		e.WriteFloat32(0, m.F32)
	}
	if m.F64 != 0 {
		e.WriteFloat64(1, m.F64)
	}
	if m.Str != "" {
		e.WriteString(2, m.Str)
	}
	if !bytes.Equal(m.BytesField, nil) {
		e.WriteBytes(3, m.BytesField)
	}
}

func (m *ExampleNested) Float32(id sofab.ID, v float32) error {
	switch id {
	case 0:
		m.F32 = v
	}
	return nil
}

func (m *ExampleNested) Float64(id sofab.ID, v float64) error {
	switch id {
	case 1:
		m.F64 = v
	}
	return nil
}

func (m *ExampleNested) String(id sofab.ID, v string) error {
	switch id {
	case 2:
		m.Str = v
	}
	return nil
}

func (m *ExampleNested) Bytes(id sofab.ID, v []byte) error {
	switch id {
	case 3:
		m.BytesField = append([]byte(nil), v...)
	}
	return nil
}
