// Code generated by sofabgen; DO NOT EDIT.

package message

import (
	"github.com/sofa-buffers/corelib-go"
)

// ExampleArrays is a generated SofaBuffers object.
type ExampleArrays struct {
	_visitorBase
	// Schema bound: count 5 is a CAPACITY, not a length -- starts empty; over 5 elements is INVALID, never truncated.
	U8 []uint8 `json:"u8"`
	// Schema bound: count 5 is a CAPACITY, not a length -- starts empty; over 5 elements is INVALID, never truncated.
	I8 []int8 `json:"i8"`
	// Schema bound: count 5 is a CAPACITY, not a length -- starts empty; over 5 elements is INVALID, never truncated.
	U16 []uint16 `json:"u16"`
	// Schema bound: count 5 is a CAPACITY, not a length -- starts empty; over 5 elements is INVALID, never truncated.
	I16 []int16 `json:"i16"`
	// Schema bound: count 5 is a CAPACITY, not a length -- starts empty; over 5 elements is INVALID, never truncated.
	U32 []uint32 `json:"u32"`
	// Schema bound: count 5 is a CAPACITY, not a length -- starts empty; over 5 elements is INVALID, never truncated.
	I32 []int32 `json:"i32"`
	// Schema bound: count 5 is a CAPACITY, not a length -- starts empty; over 5 elements is INVALID, never truncated.
	U64 []uint64 `json:"u64"`
	// Schema bound: count 5 is a CAPACITY, not a length -- starts empty; over 5 elements is INVALID, never truncated.
	I64    []int64             `json:"i64"`
	Nested ExampleArraysNested `json:"nested"`
}

func (m *ExampleArrays) Serialize(e *sofab.Encoder) {
	if len(m.U8) != 0 {
		sofab.WriteUnsignedArray(e, 0, m.U8)
	}
	if len(m.I8) != 0 {
		sofab.WriteSignedArray(e, 1, m.I8)
	}
	if len(m.U16) != 0 {
		sofab.WriteUnsignedArray(e, 2, m.U16)
	}
	if len(m.I16) != 0 {
		sofab.WriteSignedArray(e, 3, m.I16)
	}
	if len(m.U32) != 0 {
		sofab.WriteUnsignedArray(e, 4, m.U32)
	}
	if len(m.I32) != 0 {
		sofab.WriteSignedArray(e, 5, m.I32)
	}
	if len(m.U64) != 0 {
		sofab.WriteUnsignedArray(e, 6, m.U64)
	}
	if len(m.I64) != 0 {
		sofab.WriteSignedArray(e, 7, m.I64)
	}
	e.WriteSequenceBeginLazy(10)
	m.Nested.Serialize(e)
	e.WriteSequenceEnd()
}

func (m *ExampleArrays) isDefault() bool {
	if !(len(m.U8) == 0) {
		return false
	}
	if !(len(m.I8) == 0) {
		return false
	}
	if !(len(m.U16) == 0) {
		return false
	}
	if !(len(m.I16) == 0) {
		return false
	}
	if !(len(m.U32) == 0) {
		return false
	}
	if !(len(m.I32) == 0) {
		return false
	}
	if !(len(m.U64) == 0) {
		return false
	}
	if !(len(m.I64) == 0) {
		return false
	}
	if !(m.Nested.isDefault()) {
		return false
	}
	return true
}

func (m *ExampleArrays) UnsignedArray(id sofab.ID, v []uint64) error {
	switch id {
	case 0:
		if len(v) > 5 {
			return sofab.ErrInvalidMsg
		}
		for _, _x := range v {
			if _x > 255 {
				return sofab.ErrInvalidMsg
			}
		}
		m.U8 = sofab.NarrowUnsigned[uint8](v)
	case 2:
		if len(v) > 5 {
			return sofab.ErrInvalidMsg
		}
		for _, _x := range v {
			if _x > 65535 {
				return sofab.ErrInvalidMsg
			}
		}
		m.U16 = sofab.NarrowUnsigned[uint16](v)
	case 4:
		if len(v) > 5 {
			return sofab.ErrInvalidMsg
		}
		for _, _x := range v {
			if _x > 4294967295 {
				return sofab.ErrInvalidMsg
			}
		}
		m.U32 = sofab.NarrowUnsigned[uint32](v)
	case 6:
		if len(v) > 5 {
			return sofab.ErrInvalidMsg
		}
		m.U64 = v
	}
	return nil
}

func (m *ExampleArrays) SignedArray(id sofab.ID, v []int64) error {
	switch id {
	case 1:
		if len(v) > 5 {
			return sofab.ErrInvalidMsg
		}
		for _, _x := range v {
			if _x < -128 || _x > 127 {
				return sofab.ErrInvalidMsg
			}
		}
		m.I8 = sofab.NarrowSigned[int8](v)
	case 3:
		if len(v) > 5 {
			return sofab.ErrInvalidMsg
		}
		for _, _x := range v {
			if _x < -32768 || _x > 32767 {
				return sofab.ErrInvalidMsg
			}
		}
		m.I16 = sofab.NarrowSigned[int16](v)
	case 5:
		if len(v) > 5 {
			return sofab.ErrInvalidMsg
		}
		for _, _x := range v {
			if _x < -2147483648 || _x > 2147483647 {
				return sofab.ErrInvalidMsg
			}
		}
		m.I32 = sofab.NarrowSigned[int32](v)
	case 7:
		if len(v) > 5 {
			return sofab.ErrInvalidMsg
		}
		m.I64 = v
	}
	return nil
}

func (m *ExampleArrays) ArrayBegin(id sofab.ID, kind sofab.ArrayKind, count int) error {
	switch id {
	case 0:
		if kind == sofab.ArrayUnsigned && count > 5 {
			return sofab.ErrInvalidMsg
		}
	case 1:
		if kind == sofab.ArraySigned && count > 5 {
			return sofab.ErrInvalidMsg
		}
	case 2:
		if kind == sofab.ArrayUnsigned && count > 5 {
			return sofab.ErrInvalidMsg
		}
	case 3:
		if kind == sofab.ArraySigned && count > 5 {
			return sofab.ErrInvalidMsg
		}
	case 4:
		if kind == sofab.ArrayUnsigned && count > 5 {
			return sofab.ErrInvalidMsg
		}
	case 5:
		if kind == sofab.ArraySigned && count > 5 {
			return sofab.ErrInvalidMsg
		}
	case 6:
		if kind == sofab.ArrayUnsigned && count > 5 {
			return sofab.ErrInvalidMsg
		}
	case 7:
		if kind == sofab.ArraySigned && count > 5 {
			return sofab.ErrInvalidMsg
		}
	}
	return nil
}

func (m *ExampleArrays) FixlenHeader(id sofab.ID, subtype int, length int) error {
	switch id {
	}
	return nil
}

func (m *ExampleArrays) ArrayElemBound(id sofab.ID, kind sofab.ArrayKind) (int64, int64, bool) {
	switch id {
	case 0:
		if kind == sofab.ArrayUnsigned {
			return 0, 255, true
		}
	case 1:
		if kind == sofab.ArraySigned {
			return -128, 127, true
		}
	case 2:
		if kind == sofab.ArrayUnsigned {
			return 0, 65535, true
		}
	case 3:
		if kind == sofab.ArraySigned {
			return -32768, 32767, true
		}
	case 4:
		if kind == sofab.ArrayUnsigned {
			return 0, 4294967295, true
		}
	case 5:
		if kind == sofab.ArraySigned {
			return -2147483648, 2147483647, true
		}
	}
	return 0, 0, false
}

func (m *ExampleArrays) BeginSequence(id sofab.ID) (sofab.Visitor, error) {
	switch id {
	case 10:
		return &m.Nested, nil
	}
	return _visitorBase{}, nil
}

// ExampleArraysNested is a generated SofaBuffers object.
type ExampleArraysNested struct {
	_visitorBase
	// Schema bound: count 5 is a CAPACITY, not a length -- starts empty; over 5 elements is INVALID, never truncated.
	Fp32 []float32 `json:"fp32"`
	// Schema bound: count 5 is a CAPACITY, not a length -- starts empty; over 5 elements is INVALID, never truncated.
	Fp64 []float64 `json:"fp64"`
}

func (m *ExampleArraysNested) Serialize(e *sofab.Encoder) {
	if len(m.Fp32) != 0 {
		e.WriteFloat32Array(0, m.Fp32)
	}
	if len(m.Fp64) != 0 {
		e.WriteFloat64Array(1, m.Fp64)
	}
}

func (m *ExampleArraysNested) isDefault() bool {
	if !(len(m.Fp32) == 0) {
		return false
	}
	if !(len(m.Fp64) == 0) {
		return false
	}
	return true
}

func (m *ExampleArraysNested) Float32Array(id sofab.ID, v []float32) error {
	switch id {
	case 0:
		if len(v) > 5 {
			return sofab.ErrInvalidMsg
		}
		m.Fp32 = v
	}
	return nil
}

func (m *ExampleArraysNested) Float64Array(id sofab.ID, v []float64) error {
	switch id {
	case 1:
		if len(v) > 5 {
			return sofab.ErrInvalidMsg
		}
		m.Fp64 = v
	}
	return nil
}

func (m *ExampleArraysNested) ArrayBegin(id sofab.ID, kind sofab.ArrayKind, count int) error {
	switch id {
	case 0:
		if kind == sofab.ArrayFp32 && count > 5 {
			return sofab.ErrInvalidMsg
		}
	case 1:
		if kind == sofab.ArrayFp64 && count > 5 {
			return sofab.ErrInvalidMsg
		}
	}
	return nil
}

func (m *ExampleArraysNested) FixlenHeader(id sofab.ID, subtype int, length int) error {
	switch id {
	}
	return nil
}

// ExampleNested is a generated SofaBuffers object.
type ExampleNested struct {
	_visitorBase
	F64 float64 `json:"f64"`
	// Schema bound: maxlen 32 -- a longer value is INVALID, never truncated.
	Str string `json:"str"`
	// Schema bound: maxlen 4 -- a longer value is INVALID, never truncated.
	BytesField []byte  `json:"bytes_field"`
	F32        float32 `json:"f32"`
}

func (m *ExampleNested) Serialize(e *sofab.Encoder) {
	if m.F32 != 0 {
		e.WriteFloat32(0, m.F32)
	}
	if m.F64 != 0 {
		e.WriteFloat64(1, m.F64)
	}
	if m.Str != "" {
		e.WriteString(2, m.Str)
	}
	if len(m.BytesField) != 0 {
		e.WriteBytes(3, m.BytesField)
	}
}

func (m *ExampleNested) isDefault() bool {
	if !(m.F32 == 0) {
		return false
	}
	if !(m.F64 == 0) {
		return false
	}
	if !(m.Str == "") {
		return false
	}
	if !(len(m.BytesField) == 0) {
		return false
	}
	return true
}

func (m *ExampleNested) Float32(id sofab.ID, v float32) error {
	switch id {
	case 0:
		m.F32 = v
	}
	return nil
}

func (m *ExampleNested) Float64(id sofab.ID, v float64) error {
	switch id {
	case 1:
		m.F64 = v
	}
	return nil
}

func (m *ExampleNested) String(id sofab.ID, v string) error {
	switch id {
	case 2:
		if len(v) > 32 {
			return sofab.ErrInvalidMsg
		}
		if !sofab.Utf8Valid([]byte(v)) {
			return sofab.ErrInvalidMsg
		}
		m.Str = v
	}
	return nil
}

func (m *ExampleNested) Bytes(id sofab.ID, v []byte) error {
	switch id {
	case 3:
		if len(v) > 4 {
			return sofab.ErrInvalidMsg
		}
		m.BytesField = append([]byte(nil), v...)
	}
	return nil
}

func (m *ExampleNested) ArrayBegin(id sofab.ID, kind sofab.ArrayKind, count int) error {
	switch id {
	}
	return nil
}

func (m *ExampleNested) FixlenHeader(id sofab.ID, subtype int, length int) error {
	switch id {
	case 2:
		if subtype == 2 && length > 32 {
			return sofab.ErrInvalidMsg
		}
	case 3:
		if subtype == 3 && length > 4 {
			return sofab.ErrInvalidMsg
		}
	}
	return nil
}
