// Code generated by sofabgen; DO NOT EDIT.

package message

import (
	"github.com/sofa-buffers/corelib-go"
)

// ExampleArrays is a generated SofaBuffers object.
type ExampleArrays struct {
	sofab.VisitorBase
	// Schema bound: count 5 is a CAPACITY, not a length -- starts empty; over 5 elements is INVALID, never truncated.
	U8 []uint8 `json:"u8"`
	// Schema bound: count 5 is a CAPACITY, not a length -- starts empty; over 5 elements is INVALID, never truncated.
	I8 []int8 `json:"i8"`
	// Schema bound: count 5 is a CAPACITY, not a length -- starts empty; over 5 elements is INVALID, never truncated.
	U16 []uint16 `json:"u16"`
	// Schema bound: count 5 is a CAPACITY, not a length -- starts empty; over 5 elements is INVALID, never truncated.
	I16 []int16 `json:"i16"`
	// Schema bound: count 5 is a CAPACITY, not a length -- starts empty; over 5 elements is INVALID, never truncated.
	U32 []uint32 `json:"u32"`
	// Schema bound: count 5 is a CAPACITY, not a length -- starts empty; over 5 elements is INVALID, never truncated.
	I32 []int32 `json:"i32"`
	// Schema bound: count 5 is a CAPACITY, not a length -- starts empty; over 5 elements is INVALID, never truncated.
	U64 []uint64 `json:"u64"`
	// Schema bound: count 5 is a CAPACITY, not a length -- starts empty; over 5 elements is INVALID, never truncated.
	I64    []int64             `json:"i64"`
	Nested ExampleArraysNested `json:"nested"`
}

func (m *ExampleArrays) Serialize(e *sofab.Encoder) {
	if len(m.U8) != 0 {
		sofab.WriteUnsignedArray(e, 0, m.U8)
	}
	if len(m.I8) != 0 {
		sofab.WriteSignedArray(e, 1, m.I8)
	}
	if len(m.U16) != 0 {
		sofab.WriteUnsignedArray(e, 2, m.U16)
	}
	if len(m.I16) != 0 {
		sofab.WriteSignedArray(e, 3, m.I16)
	}
	if len(m.U32) != 0 {
		sofab.WriteUnsignedArray(e, 4, m.U32)
	}
	if len(m.I32) != 0 {
		sofab.WriteSignedArray(e, 5, m.I32)
	}
	if len(m.U64) != 0 {
		sofab.WriteUnsignedArray(e, 6, m.U64)
	}
	if len(m.I64) != 0 {
		sofab.WriteSignedArray(e, 7, m.I64)
	}
	e.WriteSequenceBeginLazy(10)
	m.Nested.Serialize(e)
	e.WriteSequenceEnd()
}

func (m *ExampleArrays) isDefault() bool {
	if !(len(m.U8) == 0) {
		return false
	}
	if !(len(m.I8) == 0) {
		return false
	}
	if !(len(m.U16) == 0) {
		return false
	}
	if !(len(m.I16) == 0) {
		return false
	}
	if !(len(m.U32) == 0) {
		return false
	}
	if !(len(m.I32) == 0) {
		return false
	}
	if !(len(m.U64) == 0) {
		return false
	}
	if !(len(m.I64) == 0) {
		return false
	}
	if !(m.Nested.isDefault()) {
		return false
	}
	return true
}

func (m *ExampleArrays) ArrayBegin(id sofab.ID, kind sofab.ArrayKind, count int) error {
	switch id {
	case 0:
		if kind != sofab.ArrayUnsigned {
			return nil
		}
		if count > 5 {
			return sofab.ErrInvalidMsg
		}
		m.U8 = make([]uint8, 0, count)
	case 1:
		if kind != sofab.ArraySigned {
			return nil
		}
		if count > 5 {
			return sofab.ErrInvalidMsg
		}
		m.I8 = make([]int8, 0, count)
	case 2:
		if kind != sofab.ArrayUnsigned {
			return nil
		}
		if count > 5 {
			return sofab.ErrInvalidMsg
		}
		m.U16 = make([]uint16, 0, count)
	case 3:
		if kind != sofab.ArraySigned {
			return nil
		}
		if count > 5 {
			return sofab.ErrInvalidMsg
		}
		m.I16 = make([]int16, 0, count)
	case 4:
		if kind != sofab.ArrayUnsigned {
			return nil
		}
		if count > 5 {
			return sofab.ErrInvalidMsg
		}
		m.U32 = make([]uint32, 0, count)
	case 5:
		if kind != sofab.ArraySigned {
			return nil
		}
		if count > 5 {
			return sofab.ErrInvalidMsg
		}
		m.I32 = make([]int32, 0, count)
	case 6:
		if kind != sofab.ArrayUnsigned {
			return nil
		}
		if count > 5 {
			return sofab.ErrInvalidMsg
		}
		m.U64 = make([]uint64, 0, count)
	case 7:
		if kind != sofab.ArraySigned {
			return nil
		}
		if count > 5 {
			return sofab.ErrInvalidMsg
		}
		m.I64 = make([]int64, 0, count)
	}
	return nil
}

func (m *ExampleArrays) ArrayUnsigned(id sofab.ID, _ int, v uint64) error {
	switch id {
	case 0:
		if v > 255 {
			return sofab.ErrInvalidMsg
		}
		m.U8 = append(m.U8, uint8(v))
	case 2:
		if v > 65535 {
			return sofab.ErrInvalidMsg
		}
		m.U16 = append(m.U16, uint16(v))
	case 4:
		if v > 4294967295 {
			return sofab.ErrInvalidMsg
		}
		m.U32 = append(m.U32, uint32(v))
	case 6:
		m.U64 = append(m.U64, v)
	}
	return nil
}

func (m *ExampleArrays) ArraySigned(id sofab.ID, _ int, v int64) error {
	switch id {
	case 1:
		if v < -128 || v > 127 {
			return sofab.ErrInvalidMsg
		}
		m.I8 = append(m.I8, int8(v))
	case 3:
		if v < -32768 || v > 32767 {
			return sofab.ErrInvalidMsg
		}
		m.I16 = append(m.I16, int16(v))
	case 5:
		if v < -2147483648 || v > 2147483647 {
			return sofab.ErrInvalidMsg
		}
		m.I32 = append(m.I32, int32(v))
	case 7:
		m.I64 = append(m.I64, v)
	}
	return nil
}

func (m *ExampleArrays) BeginSequence(id sofab.ID) (sofab.Visitor, error) {
	switch id {
	case 10:
		return &m.Nested, nil
	}
	return nil, nil
}

// ExampleArraysNested is a generated SofaBuffers object.
type ExampleArraysNested struct {
	sofab.VisitorBase
	// Schema bound: count 5 is a CAPACITY, not a length -- starts empty; over 5 elements is INVALID, never truncated.
	Fp32 []float32 `json:"fp32"`
	// Schema bound: count 5 is a CAPACITY, not a length -- starts empty; over 5 elements is INVALID, never truncated.
	Fp64 []float64 `json:"fp64"`
}

func (m *ExampleArraysNested) Serialize(e *sofab.Encoder) {
	if len(m.Fp32) != 0 {
		e.WriteFloat32Array(0, m.Fp32)
	}
	if len(m.Fp64) != 0 {
		e.WriteFloat64Array(1, m.Fp64)
	}
}

func (m *ExampleArraysNested) isDefault() bool {
	if !(len(m.Fp32) == 0) {
		return false
	}
	if !(len(m.Fp64) == 0) {
		return false
	}
	return true
}

func (m *ExampleArraysNested) ArrayBegin(id sofab.ID, kind sofab.ArrayKind, count int) error {
	switch id {
	case 0:
		if kind != sofab.ArrayFp32 {
			return nil
		}
		if count > 5 {
			return sofab.ErrInvalidMsg
		}
		m.Fp32 = make([]float32, 0, count)
	case 1:
		if kind != sofab.ArrayFp64 {
			return nil
		}
		if count > 5 {
			return sofab.ErrInvalidMsg
		}
		m.Fp64 = make([]float64, 0, count)
	}
	return nil
}

func (m *ExampleArraysNested) ArrayFloat32(id sofab.ID, _ int, v float32) error {
	switch id {
	case 0:
		m.Fp32 = append(m.Fp32, v)
	}
	return nil
}

func (m *ExampleArraysNested) ArrayFloat64(id sofab.ID, _ int, v float64) error {
	switch id {
	case 1:
		m.Fp64 = append(m.Fp64, v)
	}
	return nil
}

// ExampleNested is a generated SofaBuffers object.
type ExampleNested struct {
	sofab.VisitorBase
	sofab.StringCheck
	F64 float64 `json:"f64"`
	// Schema bound: maxlen 32 -- a longer value is INVALID, never truncated.
	Str string `json:"str"`
	// Schema bound: maxlen 4 -- a longer value is INVALID, never truncated.
	BytesField []byte  `json:"bytes_field"`
	F32        float32 `json:"f32"`
	// _acc assembles a string or blob payload the codec delivers in pieces
	// (S6.6.3). Unexported, so it is not part of the object's JSON form.
	_acc sofab.PayloadAcc
}

func (m *ExampleNested) Serialize(e *sofab.Encoder) {
	if m.F32 != 0 {
		e.WriteFloat32(0, m.F32)
	}
	if m.F64 != 0 {
		e.WriteFloat64(1, m.F64)
	}
	if m.Str != "" {
		e.WriteString(2, m.Str)
	}
	if len(m.BytesField) != 0 {
		e.WriteBytes(3, m.BytesField)
	}
}

func (m *ExampleNested) isDefault() bool {
	if !(m.F32 == 0) {
		return false
	}
	if !(m.F64 == 0) {
		return false
	}
	if !(m.Str == "") {
		return false
	}
	if !(len(m.BytesField) == 0) {
		return false
	}
	return true
}

func (m *ExampleNested) Float32(id sofab.ID, v float32) error {
	switch id {
	case 0:
		m.F32 = v
	}
	return nil
}

func (m *ExampleNested) Float64(id sofab.ID, v float64) error {
	switch id {
	case 1:
		m.F64 = v
	}
	return nil
}

func (m *ExampleNested) FixlenBegin(id sofab.ID, sub sofab.FixlenSubtype, total int) error {
	switch id {
	case 2:
		if sub != sofab.FixlenStr {
			return nil
		}
		if total > 32 {
			return sofab.ErrInvalidMsg
		}
	case 3:
		if sub != sofab.FixlenBlob {
			return nil
		}
		if total > 4 {
			return sofab.ErrInvalidMsg
		}
	}
	return nil
}

func (m *ExampleNested) String(id sofab.ID, total, offset int, chunk []byte) error {
	switch id {
	case 2:
		_b, _done := m._acc.Take(total, offset, chunk)
		if !_done {
			return nil
		}
		if !m.UTF8Valid(_b) {
			return sofab.ErrInvalidMsg
		}
		m.Str = string(_b)
	}
	return nil
}

func (m *ExampleNested) Bytes(id sofab.ID, total, offset int, chunk []byte) error {
	switch id {
	case 3:
		_b, _done := m._acc.Take(total, offset, chunk)
		if !_done {
			return nil
		}
		m.BytesField = append([]byte(nil), _b...)
	}
	return nil
}
