// Code generated by sofabgen; DO NOT EDIT.

package main

import (
	"encoding/hex"
	"encoding/json"
	"example.com/gen/message"
	"fmt"
	"io"
	"os"
	"reflect"
)

// benchAlignSink holds the buffer benchAlignSpan allocated last, so the
// compiler cannot decide the allocation is dead and drop it.
var benchAlignSink []byte

// benchAlignSpan pins the allocator to a known point in the size class the
// measured op allocates its output from, so that op costs the same in every
// process. Without it a bench row reading one op is bimodal by ~9%, at random.
//
// Go hands out small objects from a per-P span of one size class, and a span
// holds a handful of them -- seven, say, in the 1152-byte class a 1037-byte
// buffer falls in. Whichever allocation lands on the last slot of a span
// makes the NEXT one refill the span from mcentral -- ~1843 Ir of allocator
// slow path. Which slot the collected op gets depends on how many objects of
// that class the runtime's own start-up already took, which varies per
// process, so a fixed number of warmups cannot settle it: it only moves the
// unlucky phase somewhere else.
//
// So this does not guess the phase, it removes it. Allocating the same size
// repeatedly walks the span one object at a time -- successive addresses are
// exactly one size class apart -- until the allocator hands back one that is
// NOT adjacent, which is the first object of a fresh span. Returning there
// leaves the collected op holding the second slot of that span, in every
// process. sample is the warmup's own output, so the size class is the one
// the op actually uses and no message constant has to be threaded in here.
//
// noinline and a separate symbol, like the warmups: --toggle-collect keys on
// entering a symbol, so anything the measured op must not be charged for has
// to happen outside run_*.
//
//go:noinline
func benchAlignSpan(sample []byte) {
	n := cap(sample)
	if n == 0 {
		return
	}
	at := func() uintptr {
		b := make([]byte, n)
		benchAlignSink = b
		return reflect.ValueOf(b).Pointer()
	}
	// The stride is the size class, which is not n and is not exported by the
	// runtime -- so learn it: inside a span every step is the stride, so the
	// most common step over a short run is it, whatever the class turns out
	// to be and whichever probe straddled a span boundary.
	const probes = 32
	steps := make(map[uintptr]int, probes)
	prev := at()
	stride, seen := uintptr(0), 0
	for i := 0; i < probes; i++ {
		p := at()
		d := p - prev
		prev = p
		steps[d]++
		if steps[d] > seen {
			stride, seen = d, steps[d]
		}
	}
	// Bounded: a span cannot hold more objects than it has bytes, and a run
	// that somehow never sees a boundary must still end.
	for i := 0; i < 1<<12; i++ {
		p := at()
		if p-prev != stride {
			return
		}
		prev = p
	}
	// Falling out means no span boundary was found, so the op runs at an
	// arbitrary phase and the row is bimodal again. Say so rather than
	// returning quietly: a silent no-op here is invisible in results.txt.
	fmt.Fprintln(os.Stderr, "benchAlignSpan: no span boundary in 4096 allocations; this reading is not phase-pinned")
}

// Bench state at package scope: the results outlive the measured call so
// main can observe them after collection stops, which is what keeps the op
// from being optimized away. See tests/bench/README.md.
var benchExampleIn *message.Example
var benchExampleWire []byte
var benchExampleOut *message.Example

//go:noinline
func run_encode_example() {
	b, err := benchExampleIn.Encode()
	if err != nil {
		fail(err)
	}
	benchExampleWire = b
}

//go:noinline
func run_decode_example() {
	obj, err := message.DecodeExample(benchExampleWire)
	if err != nil {
		fail(err)
	}
	benchExampleOut = obj
}

// warmup_* pay the runtime's one-time costs (lazy itabs, type/name
// offsets, first-touch allocator spans) so the collected op does not.
// The body is DUPLICATED rather than delegating to run_*: toggling is
// keyed on entering the symbol, whoever the caller is, so a warmup that
// called run_* would be collected right along with the real op.
//
//go:noinline
func warmup_encode_example() {
	b, err := benchExampleIn.Encode()
	if err != nil {
		fail(err)
	}
	benchExampleWire = b
}

//go:noinline
func warmup_decode_example() {
	obj, err := message.DecodeExample(benchExampleWire)
	if err != nil {
		fail(err)
	}
	benchExampleOut = obj
}

// benchMain runs one op of <workload>. Everything here is setup, warmup and
// observation; only the run_* call is collected.
func benchMain(w string, in []byte) int {
	if w == "encode_example" || w == "decode_example" {
		benchExampleIn = message.NewExample()
		if err := json.Unmarshal(in, benchExampleIn); err != nil {
			fail(err)
		}
		if w == "encode_example" {
			warmup_encode_example()          // one-time runtime costs (not collected)
			benchAlignSpan(benchExampleWire) // known allocator phase (not collected)
			run_encode_example()
		} else {
			warmup_encode_example() // setup: the decode input (not collected)
			warmup_decode_example() // one-time runtime costs (not collected)
			run_decode_example()
		}
		var sink uint64
		for _, c := range benchExampleWire {
			sink = sink*31 + uint64(c)
		}
		if benchExampleOut != nil {
			j, _ := json.Marshal(benchExampleOut)
			sink += uint64(len(j))
		}
		fmt.Fprintf(os.Stderr, "sink=%d BYTES=%d\n", sink, len(benchExampleWire))
		fmt.Fprintf(os.Stderr, "wire_hex=%s\n", hex.EncodeToString(benchExampleWire))
		return 0
	}
	fmt.Fprintf(os.Stderr, "unknown workload: %s\n", w)
	return 2
}

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, "usage: harness <encode|decode|streamdecode|bench> [Message|workload]")
		os.Exit(2)
	}
	mode := os.Args[1]
	msg := "example"
	if len(os.Args) > 2 {
		msg = os.Args[2]
	}
	in, _ := io.ReadAll(os.Stdin)
	// `bench <workload>` takes a workload, not a message name.
	if mode == "bench" {
		w := ""
		if len(os.Args) > 2 {
			w = os.Args[2]
		}
		os.Exit(benchMain(w, in))
	}
	switch msg {
	case "example":
		if mode == "encode" {
			obj := message.NewExample()
			if err := json.Unmarshal(in, obj); err != nil {
				fail(err)
			}
			b, err := obj.Encode()
			if err != nil {
				fail(err)
			}
			os.Stdout.Write(b)
		} else if mode == "decode" {
			obj, err := message.DecodeExample(in)
			if err != nil {
				fail(err)
			}
			out, _ := json.Marshal(obj)
			os.Stdout.Write(out)
			fmt.Fprintln(os.Stdout)
		} else if mode == "streamdecode" {
			obj, err := message.DecodeExampleFrom(&dripReader{b: in})
			if err != nil {
				fail(err)
			}
			out, _ := json.Marshal(obj)
			os.Stdout.Write(out)
			fmt.Fprintln(os.Stdout)
		} else {
			fail(fmt.Errorf("unknown mode %q", mode))
		}
	default:
		fail(fmt.Errorf("unknown message %q", msg))
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "error:", err)
	os.Exit(1)
}

// dripReader delivers one byte per Read, so `streamdecode` drives the
// decoder across a boundary at every single position in the message. A
// bytes.Reader would hand the whole thing over in one Read and prove only
// that the signature compiles.
type dripReader struct {
	b []byte
	i int
}

func (r *dripReader) Read(p []byte) (int, error) {
	if r.i >= len(r.b) {
		return 0, io.EOF
	}
	if len(p) == 0 {
		return 0, nil
	}
	p[0] = r.b[r.i]
	r.i++
	return 1, nil
}
