// Code generated by sofabgen; DO NOT EDIT.

package main

import (
	"bytes"
	"encoding/hex"
	"encoding/json"
	"errors"
	"example.com/gen/message"
	"fmt"
	"github.com/sofa-buffers/corelib-go"
	"io"
	"math"
	"os"
	"reflect"
	"strconv"
	"strings"
)

// benchAlignSink holds the buffer benchAlignSpan allocated last, so the
// compiler cannot decide the allocation is dead and drop it.
var benchAlignSink []byte

// benchAlignSpan pins the allocator to a known point in the size class the
// measured op allocates its output from, so that op costs the same in every
// process. Without it a bench row reading one op is bimodal by ~9%, at random.
//
// Go hands out small objects from a per-P span of one size class, and a span
// holds a handful of them -- seven, say, in the 1152-byte class a 1037-byte
// buffer falls in. Whichever allocation lands on the last slot of a span
// makes the NEXT one refill the span from mcentral -- ~1843 Ir of allocator
// slow path. Which slot the collected op gets depends on how many objects of
// that class the runtime's own start-up already took, which varies per
// process, so a fixed number of warmups cannot settle it: it only moves the
// unlucky phase somewhere else.
//
// So this does not guess the phase, it removes it. Allocating the same size
// repeatedly walks the span one object at a time -- successive addresses are
// exactly one size class apart -- until the allocator hands back one that is
// NOT adjacent, which is the first object of a fresh span. Returning there
// leaves the collected op holding the second slot of that span, in every
// process. sample is the warmup's own output, so the size class is the one
// the op actually uses and no message constant has to be threaded in here.
//
// noinline and a separate symbol, like the warmups: --toggle-collect keys on
// entering a symbol, so anything the measured op must not be charged for has
// to happen outside run_*.
//
//go:noinline
func benchAlignSpan(sample []byte) {
	n := cap(sample)
	if n == 0 {
		return
	}
	at := func() uintptr {
		b := make([]byte, n)
		benchAlignSink = b
		return reflect.ValueOf(b).Pointer()
	}
	// The stride is the size class, which is not n and is not exported by the
	// runtime -- so learn it: inside a span every step is the stride, so the
	// most common step over a short run is it, whatever the class turns out
	// to be and whichever probe straddled a span boundary.
	const probes = 32
	steps := make(map[uintptr]int, probes)
	prev := at()
	stride, seen := uintptr(0), 0
	for i := 0; i < probes; i++ {
		p := at()
		d := p - prev
		prev = p
		steps[d]++
		if steps[d] > seen {
			stride, seen = d, steps[d]
		}
	}
	// Bounded: a span cannot hold more objects than it has bytes, and a run
	// that somehow never sees a boundary must still end.
	for i := 0; i < 1<<12; i++ {
		p := at()
		if p-prev != stride {
			return
		}
		prev = p
	}
	// Falling out means no span boundary was found, so the op runs at an
	// arbitrary phase and the row is bimodal again. Say so rather than
	// returning quietly: a silent no-op here is invisible in results.txt.
	fmt.Fprintln(os.Stderr, "benchAlignSpan: no span boundary in 4096 allocations; this reading is not phase-pinned")
}

// Bench state at package scope: the results outlive the measured call so
// main can observe them after collection stops, which is what keeps the op
// from being optimized away. See tests/bench/README.md.
var benchExampleIn *message.Example
var benchExampleWire []byte
var benchExampleOut *message.Example

//go:noinline
func run_encode_example() {
	b, err := benchExampleIn.Encode()
	if err != nil {
		fail(err)
	}
	benchExampleWire = b
}

//go:noinline
func run_decode_example() {
	obj, err := message.Example__Decode(benchExampleWire)
	if err != nil {
		fail(err)
	}
	benchExampleOut = obj
}

// warmup_* pay the runtime's one-time costs (lazy itabs, type/name
// offsets, first-touch allocator spans) so the collected op does not.
// The body is DUPLICATED rather than delegating to run_*: toggling is
// keyed on entering the symbol, whoever the caller is, so a warmup that
// called run_* would be collected right along with the real op.
//
//go:noinline
func warmup_encode_example() {
	b, err := benchExampleIn.Encode()
	if err != nil {
		fail(err)
	}
	benchExampleWire = b
}

//go:noinline
func warmup_decode_example() {
	obj, err := message.Example__Decode(benchExampleWire)
	if err != nil {
		fail(err)
	}
	benchExampleOut = obj
}

// benchMain runs one op of <workload>. Everything here is setup, warmup and
// observation; only the run_* call is collected.
func benchMain(w string, in []byte) int {
	if w == "encode_example" || w == "decode_example" {
		benchExampleIn = message.Example__New()
		if err := json.Unmarshal(in, benchExampleIn); err != nil {
			fail(err)
		}
		if w == "encode_example" {
			warmup_encode_example()          // one-time runtime costs (not collected)
			benchAlignSpan(benchExampleWire) // known allocator phase (not collected)
			run_encode_example()
		} else {
			warmup_encode_example() // setup: the decode input (not collected)
			warmup_decode_example() // one-time runtime costs (not collected)
			run_decode_example()
		}
		var sink uint64
		for _, c := range benchExampleWire {
			sink = sink*31 + uint64(c)
		}
		if benchExampleOut != nil {
			j, _ := json.Marshal(benchExampleOut)
			sink += uint64(len(j))
		}
		fmt.Fprintf(os.Stderr, "sink=%d BYTES=%d\n", sink, len(benchExampleWire))
		fmt.Fprintf(os.Stderr, "wire_hex=%s\n", hex.EncodeToString(benchExampleWire))
		return 0
	}
	fmt.Fprintf(os.Stderr, "unknown workload: %s\n", w)
	return 2
}

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, "usage: harness <encode|decode|streamdecode|streamencode|bench> [Message|workload]")
		os.Exit(2)
	}
	mode := os.Args[1]
	msg := "example"
	if len(os.Args) > 2 {
		msg = os.Args[2]
	}
	in, _ := io.ReadAll(os.Stdin)
	// `bench <workload>` takes a workload, not a message name.
	if mode == "bench" {
		w := ""
		if len(os.Args) > 2 {
			w = os.Args[2]
		}
		os.Exit(benchMain(w, in))
	}
	switch msg {
	case "example":
		if mode == "encode" {
			obj := message.Example__New()
			if err := unmarshalJSON(in, obj); err != nil {
				fail(err)
			}
			b, err := obj.Encode()
			if err != nil {
				fail(err)
			}
			os.Stdout.Write(b)
		} else if mode == "decode" {
			obj, err := message.Example__Decode(in)
			if err != nil {
				fail(err)
			}
			out, _ := marshalJSON(obj)
			os.Stdout.Write(out)
			fmt.Fprintln(os.Stdout)
		} else if mode == "streamdecode" {
			obj, err := message.Example__DecodeFrom(&dripReader{b: in, n: chunkArg()})
			if err != nil {
				d := sofab.NewDecoder(message.Example__New())
				d.FeedFrom(&dripReader{b: in, n: chunkArg()}, make([]byte, 4096))
				_, again := d.Feed(nil)
				fail(fmt.Errorf("%v [finish=%s]", err, verdictName(again)))
			}
			out, _ := marshalJSON(obj)
			os.Stdout.Write(out)
			fmt.Fprintln(os.Stdout)
		} else if mode == "streamencode" {
			obj := message.Example__New()
			if err := unmarshalJSON(in, obj); err != nil {
				fail(err)
			}
			var out bytes.Buffer
			if w := windowArg(); w == 0 {
				if err := obj.EncodeTo(&out); err != nil {
					fail(err)
				}
			} else {
				if w < sofab.MinOutputBuffer {
					w = sofab.MinOutputBuffer
				}
				e, err := sofab.NewEncoderSink(make([]byte, w), 0, func(_ *sofab.Encoder, b []byte) error {
					out.Write(b)
					return nil
				})
				if err != nil {
					fail(err)
				}
				obj.Serialize(e)
				if err := e.Flush(); err != nil {
					fail(err)
				}
			}
			os.Stdout.Write(out.Bytes())
		} else {
			fail(fmt.Errorf("unknown mode %q", mode))
		}
	default:
		fail(fmt.Errorf("unknown message %q", msg))
	}
}

// verdictName names the category a decoder answered with, `none` when it
// answered nothing -- which, after a refusal, is itself the failure.
func verdictName(err error) string {
	switch {
	case err == nil:
		return "none"
	case errors.Is(err, sofab.ErrLimitExceeded):
		return "LimitExceeded"
	case errors.Is(err, sofab.ErrInvalidMsg):
		return "InvalidMessage"
	}
	return err.Error()
}

// infAt is a position the input spelled in a way encoding/json cannot carry: a float
// written "inf" or "-inf", or a string written with \xNN escapes for bytes that
// are not UTF-8 (raw is then those bytes).
type infAt struct {
	path []any // map keys (string) and slice indexes (int) from the root
	neg  bool
	raw  *string
}

func jsonName(sf reflect.StructField) string {
	name, _, _ := strings.Cut(sf.Tag.Get("json"), ",")
	return name
}

// scrubInf replaces each infinity spelling at a float position of type t with
// 0 and records where it was.
func scrubInf(v any, t reflect.Type, path []any, out *[]infAt) any {
	for t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	switch x := v.(type) {
	case map[string]any:
		if t.Kind() != reflect.Struct {
			return v
		}
		for i := 0; i < t.NumField(); i++ {
			name := jsonName(t.Field(i))
			if e, ok := x[name]; ok && name != "" {
				x[name] = scrubInf(e, t.Field(i).Type, append(append([]any{}, path...), name), out)
			}
		}
	case []any:
		if t.Kind() != reflect.Slice && t.Kind() != reflect.Array {
			return v
		}
		for i, e := range x {
			x[i] = scrubInf(e, t.Elem(), append(append([]any{}, path...), i), out)
		}
	case string:
		if t.Kind() == reflect.String {
			var raw strings.Builder
			has := false
			for _, r := range x {
				if r >= 0xF700 && r <= 0xF7FF {
					raw.WriteByte(byte(r - 0xF700))
					has = true
				} else {
					raw.WriteRune(r)
				}
			}
			if has {
				s := raw.String()
				*out = append(*out, infAt{path: path, raw: &s})
				return ""
			}
		}
		if (x == "inf" || x == "-inf") && (t.Kind() == reflect.Float32 || t.Kind() == reflect.Float64) {
			*out = append(*out, infAt{path: path, neg: x == "-inf"})
			return json.Number("0")
		}
	}
	return v
}

// jsonTree is the value as encoding/json would render it, except that a float
// with no JSON number (an infinity, a NaN) becomes the string "inf", "-inf"
// or "nan". Only marshalJSON uses it, when json.Marshal has refused.
func jsonTree(v reflect.Value) any {
	switch v.Kind() {
	case reflect.Pointer, reflect.Interface:
		if v.IsNil() {
			return nil
		}
		return jsonTree(v.Elem())
	case reflect.Struct:
		m := map[string]any{}
		for i := 0; i < v.NumField(); i++ {
			if name := jsonName(v.Type().Field(i)); name != "" && name != "-" {
				m[name] = jsonTree(v.Field(i))
			}
		}
		return m
	case reflect.Slice, reflect.Array:
		if v.Kind() == reflect.Slice && v.IsNil() {
			return nil
		}
		if v.Type().Elem().Kind() == reflect.Uint8 {
			return v.Interface()
		}
		out := make([]any, v.Len())
		for i := range out {
			out[i] = jsonTree(v.Index(i))
		}
		return out
	case reflect.Float32, reflect.Float64:
		f := v.Float()
		switch {
		case math.IsNaN(f):
			return "nan"
		case math.IsInf(f, 1):
			return "inf"
		case math.IsInf(f, -1):
			return "-inf"
		}
		bits := 64
		if v.Kind() == reflect.Float32 {
			bits = 32
		}
		return json.Number(strconv.FormatFloat(f, 'g', -1, bits))
	}
	return v.Interface()
}

// marshalJSON is json.Marshal plus the output half of the infinity spelling:
// the same strings unmarshalJSON reads, so a decoded +-inf can be printed.
func marshalJSON(obj any) ([]byte, error) {
	out, err := json.Marshal(obj)
	if err == nil {
		return out, nil
	}
	return json.Marshal(jsonTree(reflect.ValueOf(obj)))
}

// byteEscapes rewrites each \xNN in the input, which JSON has no such escape for, to
// \uF7NN so the text still parses; scrubInf turns those back into the bytes.
func byteEscapes(in []byte) []byte {
	var out []byte
	for i := 0; i < len(in); i++ {
		switch {
		case in[i] == '\\' && i+1 < len(in) && in[i+1] == '\\':
			out = append(out, '\\', '\\')
			i++
		case in[i] == '\\' && i+3 < len(in) && in[i+1] == 'x':
			out = append(out, '\\', 'u', 'F', '7', in[i+2], in[i+3])
			i += 3
		default:
			out = append(out, in[i])
		}
	}
	return out
}

func unmarshalJSON(in []byte, obj any) error {
	in = byteEscapes(in)
	dec := json.NewDecoder(bytes.NewReader(in))
	dec.UseNumber() // keeps a 64-bit integer exact while the tree is rewritten
	var tree any
	if err := dec.Decode(&tree); err != nil {
		return json.Unmarshal(in, obj)
	}
	var infs []infAt
	tree = scrubInf(tree, reflect.TypeOf(obj), nil, &infs)
	clean, err := json.Marshal(tree)
	if err != nil {
		return err
	}
	if err := json.Unmarshal(clean, obj); err != nil {
		return err
	}
	for _, at := range infs {
		rv := reflect.ValueOf(obj)
		for _, p := range at.path {
			for rv.Kind() == reflect.Pointer {
				rv = rv.Elem()
			}
			switch k := p.(type) {
			case string:
				for i := 0; i < rv.NumField(); i++ {
					if jsonName(rv.Type().Field(i)) == k {
						rv = rv.Field(i)
						break
					}
				}
			case int:
				rv = rv.Index(k)
			}
		}
		if at.raw != nil {
			rv.SetString(*at.raw)
			continue
		}
		sign := 1
		if at.neg {
			sign = -1
		}
		rv.SetFloat(math.Inf(sign))
	}
	return nil
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "error:", err)
	os.Exit(1)
}

// chunkArg is `streamdecode`'s optional third argument: the bytes per Read,
// 1 by default, 0 for the whole message in one Read.
func chunkArg() int {
	if len(os.Args) > 3 {
		n, err := strconv.Atoi(os.Args[3])
		if err != nil || n < 0 {
			fail(fmt.Errorf("bad chunk size %q", os.Args[3]))
		}
		return n
	}
	return 1
}

// windowArg is `streamencode`'s third argument: the encode buffer size in
// bytes, 0 for the generated EncodeTo with its own scratch.
func windowArg() int {
	if len(os.Args) > 3 {
		n, err := strconv.Atoi(os.Args[3])
		if err != nil || n < 0 {
			fail(fmt.Errorf("bad window size %q", os.Args[3]))
		}
		return n
	}
	return 0
}

// dripReader delivers at most n bytes per Read (one by default), so
// `streamdecode` drives the decoder across a boundary at every single
// position in the message. A bytes.Reader would hand the whole thing over
// in one Read and prove only that the signature compiles. n == 0 delivers
// everything at once.
type dripReader struct {
	b []byte
	i int
	n int
}

func (r *dripReader) Read(p []byte) (int, error) {
	if r.i >= len(r.b) {
		return 0, io.EOF
	}
	if len(p) == 0 {
		return 0, nil
	}
	n := r.n
	if n == 0 {
		n = len(r.b)
	}
	if n > len(p) {
		n = len(p)
	}
	n = copy(p[:n], r.b[r.i:])
	r.i += n
	return n, nil
}
