// Code generated by sofabgen; DO NOT EDIT.

package main

import (
	"encoding/hex"
	"encoding/json"
	"example.com/gen/message"
	"fmt"
	"io"
	"os"
)

// Bench state at package scope: the results outlive the measured call so
// main can observe them after collection stops, which is what keeps the op
// from being optimized away. See tests/bench/README.md.
var benchExampleIn *message.Example
var benchExampleWire []byte
var benchExampleOut *message.Example

//go:noinline
func run_encode_example() {
	b, err := benchExampleIn.Encode()
	if err != nil {
		fail(err)
	}
	benchExampleWire = b
}

//go:noinline
func run_decode_example() {
	obj, err := message.DecodeExample(benchExampleWire)
	if err != nil {
		fail(err)
	}
	benchExampleOut = obj
}

// warmup_* pay the runtime's one-time costs (lazy itabs, type/name
// offsets, first-touch allocator spans) so the collected op does not.
// The body is DUPLICATED rather than delegating to run_*: toggling is
// keyed on entering the symbol, whoever the caller is, so a warmup that
// called run_* would be collected right along with the real op.
//
//go:noinline
func warmup_encode_example() {
	b, err := benchExampleIn.Encode()
	if err != nil {
		fail(err)
	}
	benchExampleWire = b
}

//go:noinline
func warmup_decode_example() {
	obj, err := message.DecodeExample(benchExampleWire)
	if err != nil {
		fail(err)
	}
	benchExampleOut = obj
}

// benchMain runs one op of <workload>. Everything here is setup, warmup and
// observation; only the run_* call is collected.
func benchMain(w string, in []byte) int {
	if w == "encode_example" || w == "decode_example" {
		benchExampleIn = message.NewExample()
		if err := json.Unmarshal(in, benchExampleIn); err != nil {
			fail(err)
		}
		if w == "encode_example" {
			warmup_encode_example() // one-time runtime costs (not collected)
			run_encode_example()
		} else {
			warmup_encode_example() // setup: the decode input (not collected)
			warmup_decode_example() // one-time runtime costs (not collected)
			run_decode_example()
		}
		var sink uint64
		for _, c := range benchExampleWire {
			sink = sink*31 + uint64(c)
		}
		if benchExampleOut != nil {
			j, _ := json.Marshal(benchExampleOut)
			sink += uint64(len(j))
		}
		fmt.Fprintf(os.Stderr, "sink=%d BYTES=%d\n", sink, len(benchExampleWire))
		fmt.Fprintf(os.Stderr, "wire_hex=%s\n", hex.EncodeToString(benchExampleWire))
		return 0
	}
	fmt.Fprintf(os.Stderr, "unknown workload: %s\n", w)
	return 2
}

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, "usage: harness <encode|decode|streamdecode|bench> [Message|workload]")
		os.Exit(2)
	}
	mode := os.Args[1]
	msg := "example"
	if len(os.Args) > 2 {
		msg = os.Args[2]
	}
	in, _ := io.ReadAll(os.Stdin)
	// `bench <workload>` takes a workload, not a message name.
	if mode == "bench" {
		w := ""
		if len(os.Args) > 2 {
			w = os.Args[2]
		}
		os.Exit(benchMain(w, in))
	}
	switch msg {
	case "example":
		if mode == "encode" {
			obj := message.NewExample()
			if err := json.Unmarshal(in, obj); err != nil {
				fail(err)
			}
			b, err := obj.Encode()
			if err != nil {
				fail(err)
			}
			os.Stdout.Write(b)
		} else if mode == "decode" {
			obj, err := message.DecodeExample(in)
			if err != nil {
				fail(err)
			}
			out, _ := json.Marshal(obj)
			os.Stdout.Write(out)
			fmt.Fprintln(os.Stdout)
		} else if mode == "streamdecode" {
			obj, err := message.DecodeExampleFrom(&dripReader{b: in})
			if err != nil {
				fail(err)
			}
			out, _ := json.Marshal(obj)
			os.Stdout.Write(out)
			fmt.Fprintln(os.Stdout)
		} else {
			fail(fmt.Errorf("unknown mode %q", mode))
		}
	default:
		fail(fmt.Errorf("unknown message %q", msg))
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "error:", err)
	os.Exit(1)
}

// dripReader delivers one byte per Read, so `streamdecode` drives the
// decoder across a boundary at every single position in the message. A
// bytes.Reader would hand the whole thing over in one Read and prove only
// that the signature compiles.
type dripReader struct {
	b []byte
	i int
}

func (r *dripReader) Read(p []byte) (int, error) {
	if r.i >= len(r.b) {
		return 0, io.EOF
	}
	if len(p) == 0 {
		return 0, nil
	}
	p[0] = r.b[r.i]
	r.i++
	return 1, nil
}
