#!/usr/bin/env python3
"""SofaBuffers Python benchmark target.

Encodes + decodes the canonical FullScaleExample message (schema/state.json)
through the generated `message.Example` type, which is backed by the real
corelib-py runtime. Prints one uniform BENCH line (see docs/BENCH.md).
"""
import hashlib
import json
import os
import sys
import time

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "gen"))
import message  # generated by sofabgen  # noqa: E402


def main() -> int:
    state = json.load(open(os.environ["STATE_JSON"]))
    src = message.Example.from_jsonable(state)

    # Warm-up round-trip + self-check (outside the timed region).
    blob = src.encode()
    serialized = len(blob)
    sha = hashlib.sha256(blob).hexdigest()
    if message.Example.decode(blob).encode() != blob:
        sys.stderr.write("FAIL: sofab round-trip self-check\n")
        return 1

    iters = int(os.environ.get("BENCH_ITERS", "200000"))
    t0 = time.process_time()
    for _ in range(iters):
        b = src.encode()
        message.Example.decode(b)
    t1 = time.process_time()

    cpu = t1 - t0
    mbs = (serialized * iters / cpu / 1e6) if cpu > 0 else 0.0
    print(f"BENCH lang=python impl=sofab serialized_bytes={serialized} "
          f"iters={iters} cpu_time_s={cpu:.6f} throughput_mbs={mbs:.2f} sha256={sha}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
