#!/usr/bin/env python3
"""SofaBuffers Python benchmark target.

Encodes + decodes the canonical FullScaleExample message (schema/state.json)
through the generated `message.Example` type, which is backed by the real
corelib-py runtime. Prints one uniform BENCH line (see docs/BENCH.md).

Runs twice per benchmark (see ../bench.sh), once per corelib-py engine, and
BENCH_IMPL names which one is on the line:

  sofab-native  the compiled accelerator (sofab._speedups, built by Cython)
  sofab-pure    the pure-Python fallback, forced with SOFAB_PUREPYTHON=1

Both engines are named, so this target has no plain `sofab` row: a row called
just `python` would leave which engine ran to a footnote, and that is the one
thing the pair exists to show.

Same file, same message, same iteration count — the engine is the only thing
that differs, which is exactly what the row pair isolates. The engine resolves
once, at `import sofab`, so it is the environment of THIS process that picks it;
the label is therefore checked against `sofab.IMPL` below rather than trusted.
"""
import hashlib
import json
import os
import sys
import time

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "gen"))
import message  # generated by sofabgen  # noqa: E402
import sofab  # corelib-py runtime backing message.Example  # noqa: E402


# Which engine each label must have resolved to. A mislabelled row (no compiled
# extension, or SOFAB_PUREPYTHON not honoured) would silently report one engine's
# throughput as the other's, so the mapping is asserted, not assumed.
ENGINE_FOR_IMPL = {"sofab-native": "native", "sofab-pure": "python"}


def main() -> int:
    impl = os.environ.get("BENCH_IMPL", "sofab-native")
    want = ENGINE_FOR_IMPL.get(impl)
    if want is None:
        sys.stderr.write(f"FAIL: unknown BENCH_IMPL {impl!r}\n")
        return 1
    if sofab.IMPL != want:
        sys.stderr.write(
            f"FAIL: impl={impl} expects the {want!r} corelib-py engine, "
            f"but sofab.IMPL is {sofab.IMPL!r}\n"
        )
        return 1

    state = json.load(open(os.environ["STATE_JSON"]))
    src = message.Example.from_jsonable(state)

    # Warm-up round-trip + self-check (outside the timed region).
    blob = src.encode()
    serialized = len(blob)
    sha = hashlib.sha256(blob).hexdigest()
    if message.Example.decode(blob).encode() != blob:
        sys.stderr.write(f"FAIL: {impl} round-trip self-check\n")
        return 1

    iters = int(os.environ.get("BENCH_ITERS", "200000"))
    # Chained round trip: decode the reference wire, then re-encode the freshly
    # decoded message (issue #86) — the proxy/transcode shape, which denies
    # protobuf its once-per-instance serialized-size memo so encode is measured on
    # equal terms. sink doubles as a loop-path check (every re-encode is
    # `serialized` bytes).
    sink = 0
    t0 = time.process_time()
    for _ in range(iters):
        sink += len(message.Example.decode(blob).encode())
    t1 = time.process_time()

    if sink != serialized * iters:
        sys.stderr.write(f"FAIL: {impl} loop-path self-check\n")
        return 1

    cpu = t1 - t0
    mbs = (serialized * iters / cpu / 1e6) if cpu > 0 else 0.0
    # codec reports which corelib-py backend actually ran: "native" (the compiled
    # Cython _speedups extension) or "python" (the pure-Python fallback). Same
    # bytes either way; this only surfaces whether the accelerator is in use.
    print(f"BENCH lang=python impl={impl} codec={sofab.IMPL} serialized_bytes={serialized} "
          f"iters={iters} cpu_time_s={cpu:.6f} throughput_mbs={mbs:.2f} sha256={sha}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
