#!/usr/bin/env bash
# rust-embedded target setup (embedded category):
#   sofab   = SofaBuffers corelib-rs-no-std (no_std codec), via sofabgen
#   micropb = micropb 0.6 (no_std, no-alloc protobuf), codegen in build.rs
# Idempotent: re-running regenerates + rebuilds cleanly.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
SOFABGEN="${SOFABGEN:-$ROOT/tools/sofabgen}"
SOFAB_RS_CORELIB="$ROOT/vendor/corelib-rs-no-std"
# Central pins for the generated Cargo.toml (see versions.sh header);
# renovate.json ignores sofab/gen so Renovate never fights these.
. "$ROOT/languages/versions.sh"

# Toolchain env (defensive: works both under run_benchmark.sh and standalone).
export CARGO_HOME="${CARGO_HOME:-/usr/local/cargo}"
export RUSTUP_HOME="${RUSTUP_HOME:-/usr/local/rustup}"
export PATH="/usr/local/cargo/bin:$HOME/.cargo/bin:$PATH"

# --- sofab: generate the typed message crate against corelib-rs-no-std --------
"$SOFABGEN" --config "$HERE/sofab/cfg.yaml" --lang rust \
    --in "$ROOT/schema/message.sofab.yaml" --out "$HERE/sofab/gen" >/dev/null

# Since sofabgen v0.9.0 the generated crate is a feature-gated lib+bin: the lib
# is genuinely #![no_std]/heap-free under --no-default-features (heapless types),
# and the "std" feature pulls serde/serde_json for the JSON harness. We rewrite
# Cargo.toml deterministically: substitute the ${SOFAB_RS_CORELIB} placeholder
# and add sha2 + our bench binary (both std-only), keeping the generator's
# dependency/feature set verbatim — the no_std lib build must stay untouched
# (the rust bare-metal footprint targets build exactly that).
cat > "$HERE/sofab/gen/Cargo.toml" <<EOF
# @generated by sofabgen, patched by languages/rust-embedded/setup.sh
[package]
name = "sofabuffers-generated"
version = "0.0.0"
edition = "2021"

[lib]
name = "sofabuffers_generated"
path = "src/lib.rs"

[[bin]]
name = "harness"
path = "src/main.rs"
required-features = ["std"]

[[bin]]
name = "bench"
path = "src/bench.rs"
required-features = ["std"]

[dependencies]
sofab = { package = "sofa-buffers-corelib-no-std", path = "$SOFAB_RS_CORELIB", default-features = false, features = ["array", "fixlen", "fp64", "sequence", "value64"] }
heapless = { version = "$RUST_HEAPLESS", default-features = false }
serde = { version = "1", default-features = false, features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }
sha2 = { version = "$RUST_SHA2", optional = true }

[features]
default = ["std"]
# std pulls serde + serde_json + sha2 so the JSON harness and bench build; a
# bare-metal consumer uses --no-default-features for a #![no_std], heap-free lib.
std = ["serde", "dep:serde_json", "dep:sha2"]
serde = ["dep:serde", "heapless/serde"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
EOF

# Drop our bench binary in beside the generated message module.
cp "$HERE/sofab/bench.rs" "$HERE/sofab/gen/src/bench.rs"

( cd "$HERE/sofab/gen" && cargo build --release --bin bench )

# --- micropb: micropb-gen codegen (build.rs) + no-alloc heapless codec --------
( cd "$HERE/micropb" && cargo build --release --bin bench )

echo "rust-embedded: setup OK" >&2
