#!/usr/bin/env bash
# rust-embedded target setup (embedded category):
#   sofab   = SofaBuffers corelib-rs-no-std (no_std codec), via sofabgen
#   micropb = micropb 0.6 (no_std, no-alloc protobuf), codegen in build.rs
# Idempotent: re-running regenerates + rebuilds cleanly.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
SOFABGEN="${SOFABGEN:-$ROOT/tools/sofabgen}"
SOFAB_RS_CORELIB="$ROOT/vendor/corelib-rs-no-std"

# Toolchain env (defensive: works both under run_benchmark.sh and standalone).
export CARGO_HOME="${CARGO_HOME:-/usr/local/cargo}"
export RUSTUP_HOME="${RUSTUP_HOME:-/usr/local/rustup}"
export PATH="/usr/local/cargo/bin:$HOME/.cargo/bin:$PATH"

# --- sofab: generate the typed message crate against corelib-rs-no-std --------
"$SOFABGEN" --config "$HERE/sofab/cfg.yaml" --lang rust \
    --in "$ROOT/schema/message.sofab.yaml" --out "$HERE/sofab/gen" >/dev/null

# The generator emits the sofab dep as
#   sofab = { ..., path = "${SOFAB_RS_CORELIB}", default-features = false,
#             features = ["array","fixlen","fp64","sequence","value64"] }
# We rewrite Cargo.toml deterministically: substitute the corelib path and add
# sha2 + our bench binary (keeping the generator's no_std feature set verbatim).
cat > "$HERE/sofab/gen/Cargo.toml" <<EOF
# @generated by sofabgen, patched by languages/rust-embedded/setup.sh
[package]
name = "sofabuffers-generated"
version = "0.0.0"
edition = "2021"

[dependencies]
sofab = { package = "sofa-buffers-corelib-no-std", path = "$SOFAB_RS_CORELIB", default-features = false, features = ["array", "fixlen", "fp64", "sequence", "value64"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"

[[bin]]
name = "harness"
path = "src/main.rs"

[[bin]]
name = "bench"
path = "src/bench.rs"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
EOF

# Drop our bench binary in beside the generated message module.
cp "$HERE/sofab/bench.rs" "$HERE/sofab/gen/src/bench.rs"

( cd "$HERE/sofab/gen" && cargo build --release --bin bench )

# --- micropb: micropb-gen codegen (build.rs) + no-alloc heapless codec --------
( cd "$HERE/micropb" && cargo build --release --bin bench )

echo "rust-embedded: setup OK" >&2
