#!/usr/bin/env bash
# Rust target setup: generate sofab crate + build prost protobuf crate. Idempotent.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
SOFABGEN="${SOFABGEN:-$ROOT/tools/sofabgen}"
CORELIB="$ROOT/vendor/corelib-rs"
export CARGO_HOME="${CARGO_HOME:-/usr/local/cargo}"
export RUSTUP_HOME="${RUSTUP_HOME:-/usr/local/rustup}"
export PATH="/usr/local/cargo/bin:$HOME/.cargo/bin:$PATH"
export RUSTFLAGS="${RUSTFLAGS:-} -C target-cpu=native"

# --- sofab: generate the typed message crate against corelib-rs (std) ---
"$SOFABGEN" --config "$HERE/sofab/cfg.yaml" --lang rust \
    --in "$ROOT/schema/message.sofab.yaml" --out "$HERE/sofab/gen" >/dev/null

# Wire in the std corelib path (replace the ${SOFAB_RS_CORELIB} placeholder),
# then rewrite Cargo.toml deterministically to add sha2 + our bench binary.
cat > "$HERE/sofab/gen/Cargo.toml" <<EOF
# @generated by sofabgen, patched by languages/rust/setup.sh
[package]
name = "sofabuffers-generated"
version = "0.0.0"
edition = "2021"

[dependencies]
sofab = { package = "sofa-buffers-corelib", path = "$CORELIB" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
# Keep in lockstep with languages/rust/protobuf/Cargo.toml (same row, same dep).
sha2 = "0.11"

[[bin]]
name = "harness"
path = "src/main.rs"

[[bin]]
name = "bench"
path = "src/bench.rs"

[profile.release]
lto = true
codegen-units = 1
EOF

# Drop our bench binary in beside the generated message module.
cp "$HERE/sofab/bench.rs" "$HERE/sofab/gen/src/bench.rs"

( cd "$HERE/sofab/gen" && cargo build --release --bin bench )

# --- protobuf: prost + prost-build (compiles schema/message.proto via protoc) ---
( cd "$HERE/protobuf" && cargo build --release --bin bench )

echo "rust: setup OK" >&2
