#!/usr/bin/env bash
# Rust target setup: generate sofab crate + build prost protobuf crate. Idempotent.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
SOFABGEN="${SOFABGEN:-$ROOT/tools/sofabgen}"
CORELIB="$ROOT/vendor/corelib-rs"
# Central pins for the generated Cargo.toml (see versions.sh header);
# renovate.json ignores sofab/gen so Renovate never fights these.
. "$ROOT/languages/versions.sh"
export CARGO_HOME="${CARGO_HOME:-/usr/local/cargo}"
export RUSTUP_HOME="${RUSTUP_HOME:-/usr/local/rustup}"
export PATH="/usr/local/cargo/bin:$HOME/.cargo/bin:$PATH"
export RUSTFLAGS="${RUSTFLAGS:-} -C target-cpu=native"

# --- sofab: generate the typed message crate against corelib-rs (std) ---
# Two storage profiles, one corelib and one driver (the Rust half of #107):
# sofab/cfg.yaml keeps allow_dynamic on (String/Vec), sofab-heapless/cfg.yaml
# turns it off (heapless::String<N>/heapless::Vec<T, N> — nothing on the heap).
# Both crates get the SAME sofab/bench.rs, the same $RUSTFLAGS and the same
# [profile.release]; only the generated message module and BENCH_IMPL differ, so
# the pair isolates the storage axis and nothing else.
for variant in sofab sofab-heapless; do
    "$SOFABGEN" --config "$HERE/$variant/cfg.yaml" --lang rust \
        --in "$ROOT/schema/message.sofab.yaml" --out "$HERE/$variant/gen" >/dev/null

    # Wire in the std corelib path (replace the ${SOFAB_RS_CORELIB} placeholder),
    # then rewrite Cargo.toml deterministically to add sha2 + our bench binary.
    # The heap-free profile additionally needs the heapless containers its
    # generated fields are typed with (serde feature: the JSON harness and the
    # bench deserialize state.json straight into them).
    deps="sofab = { package = \"sofa-buffers-corelib\", path = \"$CORELIB\" }"
    if [ "$variant" = sofab-heapless ]; then
        # Pinned via RUST_HEAPLESS in languages/versions.sh (shared with the
        # rust-embedded crates, which micropb holds to heapless 0.8).
        deps="$deps
heapless = { version = \"$RUST_HEAPLESS\", features = [\"serde\"] }"
    fi

    cat > "$HERE/$variant/gen/Cargo.toml" <<EOF
# @generated by sofabgen, patched by languages/rust/setup.sh
[package]
name = "sofabuffers-generated"
version = "0.0.0"
edition = "2021"

[dependencies]
$deps
serde = { version = "1", features = ["derive"] }
serde_json = "1"
# Keep in lockstep with languages/rust/protobuf/Cargo.toml (same row, same dep);
# pinned via RUST_SHA2 in languages/versions.sh.
sha2 = "$RUST_SHA2"

[[bin]]
name = "harness"
path = "src/main.rs"

[[bin]]
name = "bench"
path = "src/bench.rs"

[profile.release]
lto = true
codegen-units = 1
EOF

    # Drop our bench binary in beside the generated message module. It is the
    # same source for both profiles; BENCH_IMPL (read via option_env!) is what
    # labels the run, mirroring the C++ pair's -DBENCH_IMPL.
    cp "$HERE/sofab/bench.rs" "$HERE/$variant/gen/src/bench.rs"

    ( cd "$HERE/$variant/gen" && BENCH_IMPL="$variant" cargo build --release --bin bench )
done

# --- protobuf: prost + prost-build (compiles schema/message.proto via protoc) ---
( cd "$HERE/protobuf" && cargo build --release --bin bench )

echo "rust: setup OK" >&2
